package main

import (
	"fmt"
	"slices"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/internal/docgen"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// referencePath is the reference page a person reads.
const referencePath = "docs/reference/fine-grained-permissions.md"

// referenceIntro heads the page. %s is the GitLab release the table describes.
const referenceIntro = `# Fine-grained permissions

<!-- Generated by cmd/gen_action_grants (make gen-action-grants); do not edit. -->

What a fine-grained personal access token needs for each action this server
offers, as GitLab %s declares it. The requests come from the handlers
(` + "`docs/development/action-requests.json`" + `) and the permissions from the
authorization GitLab records for each route, GraphQL type and mutation
(` + "`docs/development/gitlab-api-live.json`" + `). Permissions are named in GitLab's
own words, as its token creation page shows them, with the boundary each is
held at: a token whose grant covers every permission of one line, at one of the
boundaries named, can run the action. Where an action has several lines, any
one of them is enough, since the action sends a different request depending on
its input. Where one of those requests is one no fine-grained token passes, the
entry says so after what the others need: the action runs, except with an input
that makes it send that request.

An action GitLab declares nothing for cannot be run with a fine-grained token at
this release, whatever the grant says: the reason is in the second column, and
a classic personal access token is the way out. **Served empty** names a part of
the answer GitLab leaves out for a fine-grained token while the rest is served:
always, or unless the grant also holds what follows it. Each part is written as
the GraphQL selection that reaches it from the field the action asks for.

Classic personal access tokens are not judged here: their scopes decide what
they can do, as before. The same requirement is served for each action in the
` + "`fine_grained`" + ` block of its ` + "`gitlab://tools/{id}`" + ` detail.
`

// renderReference writes the reference page, one table per domain.
func renderReference(table *finegrained.Table) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, referenceIntro, table.DisplayVersion())
	byDomain := map[string][][]string{}
	var domains []string
	for i := range table.Actions {
		row := &table.Actions[i]
		domain, _, _ := strings.Cut(row.ID, ".")
		if _, seen := byDomain[domain]; !seen {
			domains = append(domains, domain)
		}
		description := table.Describe(row)
		byDomain[domain] = append(byDomain[domain], []string{"`" + row.ID + "`", needsText(description), servedEmptyText(description)})
	}
	slices.Sort(domains)
	for _, domain := range domains {
		fmt.Fprintf(&b, "\n## `%s`\n\n", domain)
		b.WriteString(docgen.RenderMarkdownTable([]string{"Action", "Needs", "Served empty"}, nil, byDomain[domain]))
	}
	return []byte(b.String())
}

// needsText is what the action needs, way by way, and the ways no
// fine-grained token takes when some other way runs.
func needsText(description *finegrained.Description) string {
	if description.Denied != nil {
		return "Not reachable at this release: " + denialText(description.Denied)
	}
	ways := make([]string, len(description.AnyOf))
	for i, way := range description.AnyOf {
		ways[i] = wayText(way)
	}
	text := strings.Join(ways, " **or** ")
	if len(ways) > 1 {
		text = "one of: " + text
	}
	if len(description.DeniedWays) == 0 {
		return text
	}
	reasons := make([]string, len(description.DeniedWays))
	for i := range description.DeniedWays {
		reasons[i] = denialText(&description.DeniedWays[i])
	}
	return text + ". With an input that sends another request instead, not reachable at this release: " +
		strings.Join(reasons, " **or** ")
}

// wayText is what one way of running the action needs.
func wayText(way finegrained.Way) string {
	parts := make([]string, 0, len(way.Needs)+1)
	for _, need := range way.Needs {
		parts = append(parts, needText(need))
	}
	if way.NotJudged {
		parts = append(parts, "a request GitLab does not judge by the grant")
	}
	if len(parts) == 0 {
		return "no permission"
	}
	return strings.Join(parts, "; ")
}

// needText is one need: every permission, at one of the boundaries.
func needText(need finegrained.Need) string {
	return strings.Join(need.Permissions, ", ") + " at " + strings.Join(need.At, " or ")
}

// servedEmptyText names the parts of the answer a fine-grained token may be
// served empty.
func servedEmptyText(description *finegrained.Description) string {
	parts := make([]string, 0, len(description.AlwaysEmpty)+len(description.EmptyWithout))
	for _, selection := range description.AlwaysEmpty {
		parts = append(parts, "`"+selection+"` (always)")
	}
	for _, position := range description.EmptyWithout {
		needs := make([]string, len(position.Needs))
		for i, need := range position.Needs {
			needs[i] = needText(need)
		}
		parts = append(parts, "`"+position.Selection+"` (without "+strings.Join(needs, "; ")+")")
	}
	return strings.Join(parts, ", ")
}

// denialText says why no fine-grained token reaches an action.
func denialText(denial *finegrained.Denial) string {
	element := "`" + denial.Element + "`"
	switch denial.Cause {
	case finegrained.CauseMutationUndeclared:
		return "GitLab declares no fine-grained permission for the mutation " + element + ", and refuses it"
	case finegrained.CauseTypeUndeclared:
		return "GitLab declares no fine-grained permission for " + element + ", which the answer is made of"
	case finegrained.CausePayloadUndeclared:
		return "GitLab declares no fine-grained permission for " + element + " in the answer, so the write commits and its answer is lost"
	case finegrained.CauseBoundaryUnresolvable:
		return element + " is declared at a boundary the object the action reaches never resolves to, " + unresolvedEffect(denial.Effect)
	case finegrained.CauseRESTTodo:
		return "GitLab marks " + element + " as not yet supported for fine-grained tokens"
	default:
		return "GitLab declares no fine-grained permission for " + element
	}
}

// unresolvedEffect words what GitLab does where a boundary never resolves: a
// mutation's own check refuses it before anything runs, a write's answer is
// lost after the write commits, and a read answers null or leaves the object
// out of its list.
func unresolvedEffect(effect finegrained.Effect) string {
	switch effect {
	case finegrained.EffectRefused:
		return "so GitLab refuses the write before it runs"
	case finegrained.EffectCommittedThenNull:
		return "so the write commits and its answer is lost"
	default:
		return "so GitLab answers it as null or leaves it out of the list"
	}
}
