package main

import (
	"fmt"
	"slices"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/internal/docgen"
	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/internal/grantwords"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// referenceHead opens every language's page: the frontmatter the site reads
// the title and the description from, then the note that the page is
// generated. The site takes the title as the page's heading, so the page
// carries no heading of its own above its domains. The note is an MDX
// expression comment because MDX refuses an HTML comment, and it carries no
// space inside its delimiters because markdownlint reads "/* " as an emphasis
// marker followed by a space (MD037).
const referenceHead = "---\ntitle: %s\ndescription: \"%s\"\n---\n\n{/*Generated by cmd/gen_action_grants (make gen-action-grants); do not edit.*/}\n\n"

// referenceLanguage is one language's page: where it is written, its
// frontmatter and introduction, the heading of its first column, and the
// words a requirement is written in, which cmd/internal/grantwords holds so
// the tool reference prints the same sentence for the same action.
type referenceLanguage struct {
	// path is where the page is written, from the repository root.
	path string
	// title and description are the frontmatter; %s in description is the
	// GitLab release the table describes.
	title       string
	description string
	// intro is the introduction, one paragraph per entry; the one %s across
	// them is the GitLab release the table describes.
	intro []string
	// action heads the first column of every domain's table; the other two
	// are the words' own.
	action string
	words  *grantwords.Words
}

// referenceLanguages are the pages written, English first.
func referenceLanguages() []*referenceLanguage {
	return []*referenceLanguage{englishReference(), spanishReference()}
}

// englishReference is the English page.
func englishReference() *referenceLanguage {
	return &referenceLanguage{
		path:        "site/src/content/docs/reference/fine-grained-permissions.mdx",
		title:       "Fine-grained permissions",
		description: "What a GitLab fine-grained personal access token needs for each GitLab MCP Server action, as GitLab %s declares it: the permissions, their boundaries, and the actions no grant reaches.",
		intro: []string{
			"What a fine-grained personal access token needs for each action this server offers, as GitLab %s declares it. The requests come from the handlers ([`docs/development/action-requests.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/action-requests.json)) and the permissions from the authorization GitLab records for each route, GraphQL type and mutation ([`docs/development/gitlab-api-live.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/gitlab-api-live.json)). Permissions are named in GitLab's own words, as its token creation page shows them, with the boundary each is held at: a token whose grant covers every permission of one line, at one of the boundaries named, can run the action. Where an action has several lines, any one of them is enough, since the action sends a different request depending on its input. Where one of those requests is one no fine-grained token passes, the entry says so after what the others need: the action runs, except with an input that makes it send that request.",
			"An action GitLab declares nothing for cannot be run with a fine-grained token at this release, whatever the grant says: the reason is in the second column, and a classic personal access token is the way out. **Served empty** names a part of the answer GitLab leaves out for a fine-grained token while the rest is served: always, or unless the grant also holds what follows it. Each part is written as the GraphQL selection that reaches it from the field the action asks for.",
			"This table judges fine-grained tokens alone. The scope a classic personal access token or an OAuth token needs for each action, `read_api` or `api`, is printed on the action's entry in the [tool reference](/gitlab-mcp-server/reference/tools/), beside its tier and the line this table holds for it. The fine-grained requirement is also served for each action in the `fine_grained` block of its `gitlab://tools/{id}` detail. [Fine-grained tokens](/gitlab-mcp-server/operations/fine-grained-tokens/) covers creating a token, what the server needs from it at startup, and how a refusal reads.",
		},
		action: "Action",
		words:  grantwords.English(),
	}
}

// spanishReference is the Spanish page.
func spanishReference() *referenceLanguage {
	return &referenceLanguage{
		path:        "site/src/content/docs/es/reference/fine-grained-permissions.mdx",
		title:       "Permisos de grano fino",
		description: "Lo que necesita un token de acceso personal de grano fino de GitLab para cada acción de GitLab MCP Server, tal como lo declara GitLab %s: los permisos, sus ámbitos y las acciones que ninguna concesión alcanza.",
		intro: []string{
			"Lo que necesita un token de acceso personal de grano fino para cada acción que ofrece este servidor, tal como lo declara GitLab %s. Las peticiones salen de los handlers ([`docs/development/action-requests.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/action-requests.json)) y los permisos, de la autorización que GitLab registra para cada ruta, tipo GraphQL y mutación ([`docs/development/gitlab-api-live.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/gitlab-api-live.json)). Los permisos se nombran con las palabras del propio GitLab, tal como los muestra su página de creación de tokens, con el ámbito en que se concede cada uno: un token cuya concesión cubre todos los permisos de una línea, en uno de los ámbitos nombrados, puede ejecutar la acción. Cuando una acción tiene varias líneas, basta con cualquiera de ellas, porque la acción envía una petición distinta según su entrada. Cuando una de esas peticiones es una que ningún token de grano fino supera, la entrada lo dice después de lo que necesitan las demás: la acción se ejecuta, salvo con una entrada que le haga enviar esa petición.",
			"Una acción para la que GitLab no declara nada no se puede ejecutar con un token de grano fino en esta versión, diga lo que diga la concesión: el motivo está en la segunda columna, y la salida es un token de acceso personal clásico. **Se sirve vacío** nombra una parte de la respuesta que GitLab omite para un token de grano fino mientras sirve el resto: siempre, o salvo que la concesión tenga también lo que figura tras ella. Cada parte se escribe como la selección GraphQL que llega a ella desde el campo que pide la acción.",
			"Esta tabla juzga solo los tokens de grano fino. El scope que necesita para cada acción un token de acceso personal clásico o un token OAuth, `read_api` o `api`, figura en la entrada de la acción en la [referencia de herramientas](/gitlab-mcp-server/es/reference/tools/), junto a su nivel y a la línea que esta tabla recoge para ella. El requisito de grano fino también se sirve para cada acción en el bloque `fine_grained` de su detalle `gitlab://tools/{id}`. [Tokens de grano fino](/gitlab-mcp-server/es/operations/fine-grained-tokens/) explica cómo crear un token, qué necesita de él el servidor al arrancar y cómo se lee un rechazo.",
		},
		action: "Acción",
		words:  grantwords.Spanish(),
	}
}

// render writes the page, one table per domain.
func (l *referenceLanguage) render(table *finegrained.Table) []byte {
	version := table.DisplayVersion()
	var b strings.Builder
	fmt.Fprintf(&b, referenceHead, l.title, fmt.Sprintf(l.description, version))
	fmt.Fprintf(&b, strings.Join(l.intro, "\n\n"), version)
	b.WriteString("\n")
	byDomain := map[string][][]string{}
	var domains []string
	for i := range table.Actions {
		row := &table.Actions[i]
		domain, _, _ := strings.Cut(row.ID, ".")
		if _, seen := byDomain[domain]; !seen {
			domains = append(domains, domain)
		}
		description := table.Describe(row)
		byDomain[domain] = append(byDomain[domain], []string{"`" + row.ID + "`", l.words.NeedsText(description), l.words.ServedEmptyText(description)})
	}
	slices.Sort(domains)
	headers := []string{l.action, l.words.Needs, l.words.ServedEmpty}
	for _, domain := range domains {
		fmt.Fprintf(&b, "\n## `%s`\n\n", domain)
		b.WriteString(docgen.RenderMarkdownTable(headers, nil, byDomain[domain]))
	}
	return []byte(b.String())
}
