package main

import (
	"regexp"
	"strings"
	"testing"

	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// referenceTable is a small table the page tests render: two actions of one
// domain that read an issue, and one of another that no token reaches.
func referenceTable() *finegrained.Table {
	return &finegrained.Table{
		Version:     "19.4.1-ee",
		Permissions: []string{"read_issue"},
		Displays:    []string{"", "Issue: Read"},
		Display:     []uint16{1},
		Groups:      []finegrained.Group{{Perms: []uint16{0}, Any: finegrained.BoundaryProject}},
		Operations:  []finegrained.Operation{{Name: "GET /projects/:id/issues", Groups: []uint32{0}}},
		Actions: []finegrained.Requirement{
			{ID: "issue.get", Paths: [][]uint32{{0}}},
			{ID: "issue.list", Paths: [][]uint32{{0}}},
			{ID: "admin.thing", Denied: &finegrained.Denial{Cause: finegrained.CauseRESTUndeclared, Element: "GET /x"}},
		},
	}
}

// TestRenderReference_OneTablePerDomain verifies each language's page names
// the release it describes and holds one table per domain, in order, under
// that language's column headings, each action on its own row.
func TestRenderReference_OneTablePerDomain(t *testing.T) {
	cases := []struct {
		language *referenceLanguage
		release  string
		rows     []string
	}{
		{
			language: englishReference(),
			release:  "as GitLab 19.4.1 declares it",
			rows: []string{
				"| Action       | Needs                  | Served empty |",
				"| `issue.get`  | Issue: Read at project |", "| `issue.list` | Issue: Read at project |",
				"Not reachable at this release",
			},
		},
		{
			language: spanishReference(),
			release:  "tal como lo declara GitLab 19.4.1",
			rows: []string{
				"| Acción       | Necesita                | Se sirve vacío |",
				"| `issue.get`  | Issue: Read en proyecto |", "| `issue.list` | Issue: Read en proyecto |",
				"No alcanzable en esta versión",
			},
		},
	}
	for _, testCase := range cases {
		t.Run(testCase.language.title, func(t *testing.T) {
			page := string(testCase.language.render(referenceTable()))
			if !strings.Contains(page, testCase.release) {
				t.Error("the page does not name the release it describes")
			}
			admin, issue := strings.Index(page, "## `admin`"), strings.Index(page, "## `issue`")
			if admin < 0 || issue < admin || strings.Count(page, "## `") != 2 {
				t.Errorf("the domains are not one table each in order:\n%s", page)
			}
			for _, row := range testCase.rows {
				if !strings.Contains(page, row) {
					t.Errorf("the page holds no %q:\n%s", row, page)
				}
			}
		})
	}
}

// TestRenderReference_PointsAClassicTokenAtTheToolReference verifies each
// language's introduction says the table judges fine-grained tokens alone and
// sends the reader who holds a classic or OAuth token to the tool reference,
// where the scope each action needs is printed, in that language's own pages.
func TestRenderReference_PointsAClassicTokenAtTheToolReference(t *testing.T) {
	cases := []struct {
		language *referenceLanguage
		link     string
		scopes   string
	}{
		{englishReference(), "[tool reference](/gitlab-mcp-server/reference/tools/)", "`read_api` or `api`"},
		{spanishReference(), "[referencia de herramientas](/gitlab-mcp-server/es/reference/tools/)", "`read_api` o `api`"},
	}
	for _, testCase := range cases {
		t.Run(testCase.language.title, func(t *testing.T) {
			page := string(testCase.language.render(referenceTable()))
			for _, want := range []string{testCase.link, testCase.scopes} {
				t.Run(want, func(t *testing.T) {
					if !strings.Contains(page, want) {
						t.Errorf("the introduction holds no %q:\n%s", want, page)
					}
				})
			}
		})
	}
}

// TestRenderReference_IsASitePage verifies each page is one the documentation
// site takes: frontmatter whose title and description are one line each, the
// description naming the release, no heading of its own above the domains
// (the site makes the title the page's only top-level heading), and the
// generated-file note as an MDX comment, since MDX refuses an HTML one.
func TestRenderReference_IsASitePage(t *testing.T) {
	cases := []struct {
		language    *referenceLanguage
		title       string
		description string
	}{
		{englishReference(), "Fine-grained permissions", "as GitLab 19.4.1 declares it: the permissions"},
		{spanishReference(), "Permisos de grano fino", "tal como lo declara GitLab 19.4.1: los permisos"},
	}
	frontmatter := regexp.MustCompile(`\A---\ntitle: ([^\n]+)\ndescription: "([^"\n]+)"\n---\n\n`)
	for _, testCase := range cases {
		t.Run(testCase.title, func(t *testing.T) {
			page := string(testCase.language.render(referenceTable()))
			match := frontmatter.FindStringSubmatch(page)
			if match == nil || match[1] != testCase.title || !strings.Contains(match[2], testCase.description) {
				t.Fatalf("the page opens with no frontmatter naming %q and %q:\n%s", testCase.title, testCase.description, page)
			}
			body := page[len(match[0]):]
			if !strings.HasPrefix(body, "{/*Generated by cmd/gen_action_grants (make gen-action-grants); do not edit.*/}\n\n") {
				t.Errorf("the body does not open with the generated-file note as an MDX comment:\n%s", body)
			}
			if strings.Contains(page, "<!--") || strings.HasPrefix(body, "# ") || strings.Contains(body, "\n# ") {
				t.Errorf("the page carries an HTML comment or a heading of its own:\n%s", page)
			}
			if strings.Count(page, "%") != 0 {
				t.Errorf("the page carries a format verb left unfilled:\n%s", page)
			}
		})
	}
}

// TestReferenceLanguages_WriteTheSitePageAndItsSpanishTwin verifies the pages
// are the site's English reference page and its Spanish twin at the same path
// under es/, in that order, and that both lay out the same tables: the same
// domains, the same rows and the same action on each, which is what lets the
// site's checks hold the two pages to one layout.
func TestReferenceLanguages_WriteTheSitePageAndItsSpanishTwin(t *testing.T) {
	languages := referenceLanguages()
	if len(languages) != 2 {
		t.Fatalf("referenceLanguages = %d pages, want English and Spanish", len(languages))
	}
	english, spanish := languages[0], languages[1]
	if english.path != "site/src/content/docs/reference/fine-grained-permissions.mdx" ||
		spanish.path != "site/src/content/docs/es/reference/fine-grained-permissions.mdx" {
		t.Errorf("the pages are written to %q and %q", english.path, spanish.path)
	}
	// firstColumn is every domain heading and every row's action, in order.
	firstColumn := func(page []byte) []string {
		var rows []string
		for line := range strings.SplitSeq(string(page), "\n") {
			switch {
			case strings.HasPrefix(line, "## "):
				rows = append(rows, line)
			case strings.HasPrefix(line, "| `"):
				cell, _, _ := strings.Cut(line[1:], "|")
				rows = append(rows, strings.TrimSpace(cell))
			}
		}
		return rows
	}
	table := referenceTable()
	en, es := firstColumn(english.render(table)), firstColumn(spanish.render(table))
	if strings.Join(en, "\n") != strings.Join(es, "\n") || len(en) != 5 {
		t.Errorf("the pages lay out different tables:\nEnglish %q\nSpanish %q", en, es)
	}
}
