package main

import (
	"fmt"
	"slices"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/internal/docgen"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// referenceHead opens every language's page: the frontmatter the site reads
// the title and the description from, then the note that the page is
// generated. The site takes the title as the page's heading, so the page
// carries no heading of its own above its domains. The note is an MDX
// expression comment because MDX refuses an HTML comment, and it carries no
// space inside its delimiters because markdownlint reads "/* " as an emphasis
// marker followed by a space (MD037).
const referenceHead = "---\ntitle: %s\ndescription: \"%s\"\n---\n\n{/*Generated by cmd/gen_action_grants (make gen-action-grants); do not edit.*/}\n\n"

// referenceLanguage is the wording of one language's page: where it is
// written, its frontmatter and introduction, the table headings, and every
// phrase a row is made of. Action IDs, permission names, the GraphQL
// selections and the elements GitLab names stay as they are in every
// language, since a reader matches them against GitLab and this server rather
// than reads them as prose.
type referenceLanguage struct {
	// path is where the page is written, from the repository root.
	path string
	// title and description are the frontmatter; %s in description is the
	// GitLab release the table describes.
	title       string
	description string
	// intro is the introduction, one paragraph per entry; the one %s across
	// them is the GitLab release the table describes.
	intro []string
	// headers are the three columns of every domain's table.
	headers []string

	// notReachable opens the entry of an action no fine-grained token runs.
	notReachable string
	// oneOf opens the entry of an action with several ways of running.
	oneOf string
	// or separates ways, and the denials of the ways no token takes.
	or string
	// deniedWays leads into the ways no fine-grained token takes, after what
	// the others need.
	deniedWays string
	// notJudged is a request GitLab leaves out of the grant check.
	notJudged string
	// noPermission is a way that needs nothing.
	noPermission string
	// at joins a need's permissions to its boundaries, and boundaryOr joins
	// the boundaries.
	at         string
	boundaryOr string
	// boundaries are the words a boundary is written in where they are not
	// GitLab's own; a boundary it does not hold is written as GitLab names it.
	boundaries map[string]string
	// always and without close a part of the answer served empty: always, or
	// unless the grant holds what follows without.
	always  string
	without string

	// The denials, one format per cause; each %s is the element GitLab
	// names, and unresolvable's second %s is what GitLab does about it.
	mutationUndeclared string
	typeUndeclared     string
	payloadUndeclared  string
	unresolvable       string
	restTodo           string
	undeclared         string
	// The effects of a boundary that never resolves.
	effectRefused   string
	effectCommitted string
	effectNull      string
}

// referenceLanguages are the pages written, English first.
func referenceLanguages() []*referenceLanguage {
	return []*referenceLanguage{englishReference(), spanishReference()}
}

// englishReference is the English page.
func englishReference() *referenceLanguage {
	return &referenceLanguage{
		path:        "site/src/content/docs/reference/fine-grained-permissions.mdx",
		title:       "Fine-grained permissions",
		description: "What a GitLab fine-grained personal access token needs for each GitLab MCP Server action, as GitLab %s declares it: the permissions, their boundaries, and the actions no grant reaches.",
		intro: []string{
			"What a fine-grained personal access token needs for each action this server offers, as GitLab %s declares it. The requests come from the handlers ([`docs/development/action-requests.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/action-requests.json)) and the permissions from the authorization GitLab records for each route, GraphQL type and mutation ([`docs/development/gitlab-api-live.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/gitlab-api-live.json)). Permissions are named in GitLab's own words, as its token creation page shows them, with the boundary each is held at: a token whose grant covers every permission of one line, at one of the boundaries named, can run the action. Where an action has several lines, any one of them is enough, since the action sends a different request depending on its input. Where one of those requests is one no fine-grained token passes, the entry says so after what the others need: the action runs, except with an input that makes it send that request.",
			"An action GitLab declares nothing for cannot be run with a fine-grained token at this release, whatever the grant says: the reason is in the second column, and a classic personal access token is the way out. **Served empty** names a part of the answer GitLab leaves out for a fine-grained token while the rest is served: always, or unless the grant also holds what follows it. Each part is written as the GraphQL selection that reaches it from the field the action asks for.",
			"Classic personal access tokens are not judged here: their scopes decide what they can do, as before. The same requirement is served for each action in the `fine_grained` block of its `gitlab://tools/{id}` detail. [Fine-grained tokens](/gitlab-mcp-server/operations/fine-grained-tokens/) covers creating a token, what the server needs from it at startup, and how a refusal reads.",
		},
		headers:            []string{"Action", "Needs", "Served empty"},
		notReachable:       "Not reachable at this release: ",
		oneOf:              "one of: ",
		or:                 " **or** ",
		deniedWays:         ". With an input that sends another request instead, not reachable at this release: ",
		notJudged:          "a request GitLab does not judge by the grant",
		noPermission:       "no permission",
		at:                 " at ",
		boundaryOr:         " or ",
		always:             " (always)",
		without:            " (without ",
		mutationUndeclared: "GitLab declares no fine-grained permission for the mutation %s, and refuses it",
		typeUndeclared:     "GitLab declares no fine-grained permission for %s, which the answer is made of",
		payloadUndeclared:  "GitLab declares no fine-grained permission for %s in the answer, so the write commits and its answer is lost",
		unresolvable:       "%s is declared at a boundary the object the action reaches never resolves to, %s",
		restTodo:           "GitLab marks %s as not yet supported for fine-grained tokens",
		undeclared:         "GitLab declares no fine-grained permission for %s",
		effectRefused:      "so GitLab refuses the write before it runs",
		effectCommitted:    "so the write commits and its answer is lost",
		effectNull:         "so GitLab answers it as null or leaves it out of the list",
	}
}

// spanishReference is the Spanish page. A boundary is written the way the
// Spanish fine-grained tokens guide names it.
func spanishReference() *referenceLanguage {
	return &referenceLanguage{
		path:        "site/src/content/docs/es/reference/fine-grained-permissions.mdx",
		title:       "Permisos de grano fino",
		description: "Lo que necesita un token de acceso personal de grano fino de GitLab para cada acción de GitLab MCP Server, tal como lo declara GitLab %s: los permisos, sus ámbitos y las acciones que ninguna concesión alcanza.",
		intro: []string{
			"Lo que necesita un token de acceso personal de grano fino para cada acción que ofrece este servidor, tal como lo declara GitLab %s. Las peticiones salen de los handlers ([`docs/development/action-requests.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/action-requests.json)) y los permisos, de la autorización que GitLab registra para cada ruta, tipo GraphQL y mutación ([`docs/development/gitlab-api-live.json`](https://github.com/jmrplens/gitlab-mcp-server/blob/main/docs/development/gitlab-api-live.json)). Los permisos se nombran con las palabras del propio GitLab, tal como los muestra su página de creación de tokens, con el ámbito en que se concede cada uno: un token cuya concesión cubre todos los permisos de una línea, en uno de los ámbitos nombrados, puede ejecutar la acción. Cuando una acción tiene varias líneas, basta con cualquiera de ellas, porque la acción envía una petición distinta según su entrada. Cuando una de esas peticiones es una que ningún token de grano fino supera, la entrada lo dice después de lo que necesitan las demás: la acción se ejecuta, salvo con una entrada que le haga enviar esa petición.",
			"Una acción para la que GitLab no declara nada no se puede ejecutar con un token de grano fino en esta versión, diga lo que diga la concesión: el motivo está en la segunda columna, y la salida es un token de acceso personal clásico. **Se sirve vacío** nombra una parte de la respuesta que GitLab omite para un token de grano fino mientras sirve el resto: siempre, o salvo que la concesión tenga también lo que figura tras ella. Cada parte se escribe como la selección GraphQL que llega a ella desde el campo que pide la acción.",
			"Los tokens de acceso personal clásicos no se juzgan aquí: sus scopes deciden lo que pueden hacer, como hasta ahora. El mismo requisito se sirve para cada acción en el bloque `fine_grained` de su detalle `gitlab://tools/{id}`. [Tokens de grano fino](/gitlab-mcp-server/es/operations/fine-grained-tokens/) explica cómo crear un token, qué necesita de él el servidor al arrancar y cómo se lee un rechazo.",
		},
		headers:      []string{"Acción", "Necesita", "Se sirve vacío"},
		notReachable: "No alcanzable en esta versión: ",
		oneOf:        "una de: ",
		or:           " **o** ",
		deniedWays:   ". Con una entrada que envía otra petición en su lugar, no alcanzable en esta versión: ",
		notJudged:    "una petición que GitLab no juzga por la concesión",
		noPermission: "ningún permiso",
		at:           " en ",
		boundaryOr:   " o ",
		boundaries: map[string]string{
			"project":  "proyecto",
			"group":    "grupo",
			"user":     "usuario",
			"instance": "instancia",
		},
		always:             " (siempre)",
		without:            " (sin ",
		mutationUndeclared: "GitLab no declara ningún permiso de grano fino para la mutación %s, y la rechaza",
		typeUndeclared:     "GitLab no declara ningún permiso de grano fino para %s, del que está hecha la respuesta",
		payloadUndeclared:  "GitLab no declara ningún permiso de grano fino para %s en la respuesta, así que la escritura se confirma y su respuesta se pierde",
		unresolvable:       "%s se declara en un ámbito al que nunca se resuelve el objeto que alcanza la acción, %s",
		restTodo:           "GitLab marca %s como aún no admitido para tokens de grano fino",
		undeclared:         "GitLab no declara ningún permiso de grano fino para %s",
		effectRefused:      "así que GitLab rechaza la escritura antes de que se ejecute",
		effectCommitted:    "así que la escritura se confirma y su respuesta se pierde",
		effectNull:         "así que GitLab lo responde como null o lo deja fuera de la lista",
	}
}

// render writes the page, one table per domain.
func (l *referenceLanguage) render(table *finegrained.Table) []byte {
	version := table.DisplayVersion()
	var b strings.Builder
	fmt.Fprintf(&b, referenceHead, l.title, fmt.Sprintf(l.description, version))
	fmt.Fprintf(&b, strings.Join(l.intro, "\n\n"), version)
	b.WriteString("\n")
	byDomain := map[string][][]string{}
	var domains []string
	for i := range table.Actions {
		row := &table.Actions[i]
		domain, _, _ := strings.Cut(row.ID, ".")
		if _, seen := byDomain[domain]; !seen {
			domains = append(domains, domain)
		}
		description := table.Describe(row)
		byDomain[domain] = append(byDomain[domain], []string{"`" + row.ID + "`", l.needsText(description), l.servedEmptyText(description)})
	}
	slices.Sort(domains)
	for _, domain := range domains {
		fmt.Fprintf(&b, "\n## `%s`\n\n", domain)
		b.WriteString(docgen.RenderMarkdownTable(l.headers, nil, byDomain[domain]))
	}
	return []byte(b.String())
}

// needsText is what the action needs, way by way, and the ways no
// fine-grained token takes when some other way runs.
func (l *referenceLanguage) needsText(description *finegrained.Description) string {
	if description.Denied != nil {
		return l.notReachable + l.denialText(description.Denied)
	}
	ways := make([]string, len(description.AnyOf))
	for i, way := range description.AnyOf {
		ways[i] = l.wayText(way)
	}
	text := strings.Join(ways, l.or)
	if len(ways) > 1 {
		text = l.oneOf + text
	}
	if len(description.DeniedWays) == 0 {
		return text
	}
	reasons := make([]string, len(description.DeniedWays))
	for i := range description.DeniedWays {
		reasons[i] = l.denialText(&description.DeniedWays[i])
	}
	return text + l.deniedWays + strings.Join(reasons, l.or)
}

// wayText is what one way of running the action needs.
func (l *referenceLanguage) wayText(way finegrained.Way) string {
	parts := make([]string, 0, len(way.Needs)+1)
	for _, need := range way.Needs {
		parts = append(parts, l.needText(need))
	}
	if way.NotJudged {
		parts = append(parts, l.notJudged)
	}
	if len(parts) == 0 {
		return l.noPermission
	}
	return strings.Join(parts, "; ")
}

// needText is one need: every permission, at one of the boundaries.
func (l *referenceLanguage) needText(need finegrained.Need) string {
	boundaries := make([]string, len(need.At))
	for i, boundary := range need.At {
		boundaries[i] = l.boundary(boundary)
	}
	return strings.Join(need.Permissions, ", ") + l.at + strings.Join(boundaries, l.boundaryOr)
}

// boundary is one boundary in the page's words.
func (l *referenceLanguage) boundary(name string) string {
	if word, ok := l.boundaries[name]; ok {
		return word
	}
	return name
}

// servedEmptyText names the parts of the answer a fine-grained token may be
// served empty.
func (l *referenceLanguage) servedEmptyText(description *finegrained.Description) string {
	var parts []string
	for _, selection := range description.AlwaysEmpty {
		parts = append(parts, "`"+selection+"`"+l.always)
	}
	for _, position := range description.EmptyWithout {
		needs := make([]string, len(position.Needs))
		for i, need := range position.Needs {
			needs[i] = l.needText(need)
		}
		parts = append(parts, "`"+position.Selection+"`"+l.without+strings.Join(needs, "; ")+")")
	}
	return strings.Join(parts, ", ")
}

// denialText says why no fine-grained token reaches an action.
func (l *referenceLanguage) denialText(denial *finegrained.Denial) string {
	element := "`" + denial.Element + "`"
	switch denial.Cause {
	case finegrained.CauseMutationUndeclared:
		return fmt.Sprintf(l.mutationUndeclared, element)
	case finegrained.CauseTypeUndeclared:
		return fmt.Sprintf(l.typeUndeclared, element)
	case finegrained.CausePayloadUndeclared:
		return fmt.Sprintf(l.payloadUndeclared, element)
	case finegrained.CauseBoundaryUnresolvable:
		return fmt.Sprintf(l.unresolvable, element, l.unresolvedEffect(denial.Effect))
	case finegrained.CauseRESTTodo:
		return fmt.Sprintf(l.restTodo, element)
	default:
		return fmt.Sprintf(l.undeclared, element)
	}
}

// unresolvedEffect words what GitLab does where a boundary never resolves: a
// mutation's own check refuses it before anything runs, a write's answer is
// lost after the write commits, and a read answers null or leaves the object
// out of its list.
func (l *referenceLanguage) unresolvedEffect(effect finegrained.Effect) string {
	switch effect {
	case finegrained.EffectRefused:
		return l.effectRefused
	case finegrained.EffectCommittedThenNull:
		return l.effectCommitted
	default:
		return l.effectNull
	}
}
