package main

import (
	"encoding/json"

	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/gen_action_grants/internal/derive"
	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/gen_action_grants/internal/join"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/cmdutil"
)

// requestsPath is the committed record of what each action sends.
const requestsPath = "docs/development/action-requests.json"

// requestsNote heads the record, so a reader arriving at the file knows what
// it is and where it comes from.
const requestsNote = "Generated by cmd/gen_action_grants from the handlers (make gen-action-grants); do not edit. " +
	"Per catalog action, the REST routes, in the live GitLab record's spelling, and the GraphQL operations its " +
	"handler can send, each classified by the paths that make it: mandatory on every path, an alternative on some, " +
	"optional on none. Where a request comes from is named by symbol, never by line, so a change to a handler shows " +
	"here as a change to what it sends."

// requestsRecord is the file.
type requestsRecord struct {
	Note    string          `json:"note"`
	Actions []requestAction `json:"actions"`
}

// requestAction is one action.
type requestAction struct {
	ID          string         `json:"id"`
	Handlers    []string       `json:"handlers"`
	Declaration string         `json:"declaration,omitempty"`
	Requests    []requestEntry `json:"requests,omitempty"`
	// Paths are the ways the action runs, as indices into Requests.
	Paths [][]int `json:"paths"`
}

// requestEntry is one request of one action.
type requestEntry struct {
	Kind derive.Kind `json:"kind"`
	// Route is a REST request's route as the live record spells it, and
	// Derived the derivation's spelling where a declaration placed it.
	Route   string `json:"route,omitempty"`
	Derived string `json:"derived,omitempty"`
	// Operation, RootFields and Positions describe a GraphQL request.
	Operation  string       `json:"operation,omitempty"`
	RootFields []string     `json:"root_fields,omitempty"`
	Positions  []string     `json:"positions,omitempty"`
	Reason     string       `json:"reason,omitempty"`
	Class      derive.Class `json:"class"`
	Sites      []string     `json:"sites,omitempty"`
	SDKMethods []string     `json:"sdk_methods,omitempty"`
	Directives []string     `json:"directives,omitempty"`
	// Declaration is the category of the declaration that supplied it.
	Declaration string `json:"declaration,omitempty"`
}

// renderRequests renders the record of what every action sends.
func renderRequests(actions []join.Action) []byte {
	record := requestsRecord{Note: requestsNote, Actions: []requestAction{}}
	for _, act := range actions {
		entry := requestAction{ID: act.ID, Handlers: act.Handlers, Declaration: act.Declaration, Paths: act.Paths}
		if entry.Paths == nil {
			entry.Paths = [][]int{}
		}
		for _, request := range act.Requests {
			item := requestEntry{
				Kind: request.Kind, Class: request.Class, Sites: request.Sites, SDKMethods: request.SDKMethods,
				Directives: request.Directives, Declaration: request.Declaration,
			}
			switch request.Kind {
			case derive.KindREST:
				item.Route, item.Derived = request.Name, request.Route
			case derive.KindGraphQL:
				item.Operation, item.RootFields, item.Positions = request.Name, request.RootFields, request.Positions
			default:
				item.Reason = request.Reason
			}
			entry.Requests = append(entry.Requests, item)
		}
		record.Actions = append(record.Actions, entry)
	}
	// Marshaling slices, strings and maps of them cannot fail, and the
	// repository's rule for that is to say so at the leaf.
	return cmdutil.Must(json.MarshalIndent(record, "", "  "))
}
