package main

import (
	"bytes"
	"fmt"
	"go/format"
	"maps"
	"slices"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/jmrplens/gitlab-mcp-server/v3/internal/cmdutil"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// tablePath is the generated table the server compiles in.
const tablePath = "internal/tools/actiongrants/table_gen.go"

// tableHeader opens the file. The first line is the form Go's tools read as
// "generated", so linters and reviewers skip it.
const tableHeader = `// Code generated by cmd/gen_action_grants; DO NOT EDIT.

package actiongrants

import "github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"

// table is what a fine-grained token needs for each catalog action at the
// GitLab release the live record was taken from: the join of the requests the
// handlers send (docs/development/action-requests.json) with the
// authorization GitLab declares for them (docs/development/gitlab-api-live.json).
// Every value is a constant, so the compiler lays it out as data and the
// binary runs no code to build it.
var table = finegrained.Table{
`

// boundaryConstants spells each boundary bit as the constant that names it,
// in the order finegrained.Boundary.Names reads them.
var boundaryConstants = map[string]string{
	"project":  "finegrained.BoundaryProject",
	"group":    "finegrained.BoundaryGroup",
	"user":     "finegrained.BoundaryUser",
	"instance": "finegrained.BoundaryInstance",
}

// causeConstants and effectConstants spell each cause and effect as the
// constant that names it, so the table reads the vocabulary finegrained
// declares rather than repeating its values.
var (
	causeConstants = map[finegrained.Cause]string{
		finegrained.CauseMutationUndeclared:   "finegrained.CauseMutationUndeclared",
		finegrained.CauseTypeUndeclared:       "finegrained.CauseTypeUndeclared",
		finegrained.CausePayloadUndeclared:    "finegrained.CausePayloadUndeclared",
		finegrained.CauseBoundaryUnresolvable: "finegrained.CauseBoundaryUnresolvable",
		finegrained.CauseRESTTodo:             "finegrained.CauseRESTTodo",
		finegrained.CauseRESTUndeclared:       "finegrained.CauseRESTUndeclared",
		finegrained.CauseNotGranted:           "finegrained.CauseNotGranted",
	}
	effectConstants = map[finegrained.Effect]string{
		finegrained.EffectNull:              "finegrained.EffectNull",
		finegrained.EffectNullOrEmpty:       "finegrained.EffectNullOrEmpty",
		finegrained.EffectRemoved:           "finegrained.EffectRemoved",
		finegrained.EffectListNull:          "finegrained.EffectListNull",
		finegrained.EffectRefused:           "finegrained.EffectRefused",
		finegrained.EffectCommittedThenNull: "finegrained.EffectCommittedThenNull",
	}
)

// renderTable writes the table as Go source of keyed composite literals, so a
// field added to a finegrained type leaves an older table compiling. The
// words a permission is offered by are declared once each, as constants
// after the table, since many raw permissions share one assignable.
func renderTable(table *finegrained.Table) []byte {
	var b bytes.Buffer
	b.WriteString(tableHeader)
	fmt.Fprintf(&b, "Version: %q,\nBucket: %q,\n", table.Version, table.Bucket)
	writeStrings(&b, "Permissions", table.Permissions)
	displays := displayConstants(table.Display)
	b.WriteString("Display: []string{\n")
	for _, display := range table.Display {
		if display == "" {
			b.WriteString(`"",` + "\n")
			continue
		}
		b.WriteString(displays[display] + ",\n")
	}
	b.WriteString("},\n")
	b.WriteString("Assignables: []finegrained.Assignable{\n")
	for _, a := range table.Assignables {
		fmt.Fprintf(&b, "{Name: %q, Permissions: %s, Boundaries: %s", a.Name, uint16s(a.Permissions), boundary(a.Boundaries))
		writeFlag(&b, "Deprecated", a.Deprecated)
		writeFlag(&b, "Grantable", a.Grantable)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
	b.WriteString("PublicAnonymous: [2][]uint64{\n")
	for _, set := range table.PublicAnonymous {
		b.WriteString(uint64s(set) + ",\n")
	}
	b.WriteString("},\n")
	fmt.Fprintf(&b, "PublicKnown: %t,\n", table.PublicKnown)
	b.WriteString("Groups: []finegrained.Group{\n")
	for _, g := range table.Groups {
		fmt.Fprintf(&b, "{Perms: %s, Any: %s},\n", uint16s(g.Perms), boundary(g.Any))
	}
	b.WriteString("},\n")
	b.WriteString("Operations: []finegrained.Operation{\n")
	for _, op := range table.Operations {
		fmt.Fprintf(&b, "{Name: %q", op.Name)
		writeIndices(&b, "Groups", op.Groups)
		writeFlag(&b, "Skip", op.Skip)
		writeIndices(&b, "Spine", op.Spine)
		writeIndices(&b, "OffSpine", op.OffSpine)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
	b.WriteString("Elements: []finegrained.Element{\n")
	for _, e := range table.Elements {
		fmt.Fprintf(&b, "{Path: %q, Type: %q", e.Path, e.Type)
		if len(e.Members) > 0 {
			b.WriteString(", Members: " + quoted(e.Members))
		}
		writeIndices(&b, "Groups", e.Groups)
		writeFlag(&b, "Undeclared", e.Undeclared)
		fmt.Fprintf(&b, ", Effect: %s},\n", constantOf(effectConstants, e.Effect))
	}
	b.WriteString("},\n")
	b.WriteString("Actions: []finegrained.Requirement{\n")
	for _, row := range table.Actions {
		fmt.Fprintf(&b, "{ID: %q", row.ID)
		if len(row.Paths) > 0 {
			paths := make([]string, len(row.Paths))
			for i, path := range row.Paths {
				paths[i] = uint32s(path)[len("[]uint32"):]
			}
			b.WriteString(", Paths: [][]uint32{" + strings.Join(paths, ", ") + "}")
		}
		if row.Denied != nil {
			fmt.Fprintf(&b, ", Denied: &finegrained.Denial%s", denial(*row.Denied))
		}
		if len(row.DeniedWays) > 0 {
			ways := make([]string, len(row.DeniedWays))
			for i, way := range row.DeniedWays {
				ways[i] = denial(way)
			}
			b.WriteString(", DeniedWays: []finegrained.Denial{" + strings.Join(ways, ", ") + "}")
		}
		writeIndices(&b, "Degraded", row.Degraded)
		writeFlag(&b, "GraphQL", row.GraphQL)
		writeFlag(&b, "Collection", row.Collection)
		b.WriteString("},\n")
	}
	b.WriteString("},\n}\n")
	writeDisplayConstants(&b, displays)
	// The source is assembled from fixed fragments and quoted values, so a
	// formatting failure is a defect of this function, which the repository's
	// rule says to state at the leaf.
	return cmdutil.Must(format.Source(b.Bytes()))
}

// denial spells one denial's fields as a keyed literal body.
func denial(d finegrained.Denial) string {
	return fmt.Sprintf("{Cause: %s, Element: %q, Effect: %s}",
		constantOf(causeConstants, d.Cause), d.Element, constantOf(effectConstants, d.Effect))
}

// constantOf spells a cause or an effect as the constant that names it. A
// value finegrained declares and this table does not name is a defect of the
// table above, which the repository's rule says to state at the leaf.
func constantOf[V ~string](names map[V]string, value V) string {
	name, ok := names[value]
	if !ok {
		cmdutil.MustDo(fmt.Errorf("%T %q has no constant in the table writer", value, value))
	}
	return name
}

// displayConstants names every distinct non-empty display as a Go constant:
// display followed by its words, each capitalized, with everything but
// letters and digits dropped ("CI/CD Setting: Update" is
// displayCICDSettingUpdate). Two displays that spell one name, which only a
// difference in case or punctuation can cause, are told apart by a number
// after the second, in sorted order so the names do not move between runs.
func displayConstants(displays []string) map[string]string {
	distinct := slices.Sorted(maps.Keys(setOf(displays)))
	names := make(map[string]string, len(distinct))
	taken := map[string]bool{}
	for _, display := range distinct {
		if display == "" {
			continue
		}
		base := displayIdentifier(display)
		name := base
		for n := 2; taken[name]; n++ {
			name = base + strconv.Itoa(n)
		}
		taken[name] = true
		names[display] = name
	}
	return names
}

// displayIdentifier spells one display as an identifier, without telling
// collisions apart.
func displayIdentifier(display string) string {
	var b strings.Builder
	b.WriteString("display")
	words := strings.FieldsFunc(display, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	for _, word := range words {
		first, size := utf8.DecodeRuneInString(word)
		b.WriteRune(unicode.ToUpper(first))
		b.WriteString(word[size:])
	}
	return b.String()
}

// writeDisplayConstants declares the display constants, sorted by name.
func writeDisplayConstants(b *bytes.Buffer, names map[string]string) {
	if len(names) == 0 {
		return
	}
	byName := make(map[string]string, len(names))
	for display, name := range names {
		byName[name] = display
	}
	b.WriteString("\n// The words GitLab's token page offers each assignable permission by, which\n" +
		"// Display reads once per raw permission the assignable expands to.\nconst (\n")
	for _, name := range slices.Sorted(maps.Keys(byName)) {
		fmt.Fprintf(b, "%s = %q\n", name, byName[name])
	}
	b.WriteString(")\n")
}

// setOf is the set of a slice's values.
func setOf(values []string) map[string]bool {
	set := make(map[string]bool, len(values))
	for _, value := range values {
		set[value] = true
	}
	return set
}

// writeStrings writes a string slice field, one value per line.
func writeStrings(b *bytes.Buffer, field string, values []string) {
	fmt.Fprintf(b, "%s: []string{\n", field)
	for _, v := range values {
		fmt.Fprintf(b, "%q,\n", v)
	}
	b.WriteString("},\n")
}

// writeIndices writes an index slice field when it holds anything.
func writeIndices(b *bytes.Buffer, field string, values []uint32) {
	if len(values) > 0 {
		fmt.Fprintf(b, ", %s: %s", field, uint32s(values))
	}
}

// writeFlag writes a boolean field when it is set.
func writeFlag(b *bytes.Buffer, field string, set bool) {
	if set {
		fmt.Fprintf(b, ", %s: true", field)
	}
}

// boundary spells a boundary set as an expression of the constants.
func boundary(set finegrained.Boundary) string {
	names := set.Names()
	if len(names) == 0 {
		return "0"
	}
	parts := make([]string, len(names))
	for i, name := range names {
		parts[i] = boundaryConstants[name]
	}
	return strings.Join(parts, " | ")
}

// uint16s spells an index slice.
func uint16s(values []uint16) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.FormatUint(uint64(v), 10)
	}
	return "[]uint16{" + strings.Join(parts, ", ") + "}"
}

// uint32s spells an index slice.
func uint32s(values []uint32) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.FormatUint(uint64(v), 10)
	}
	return "[]uint32{" + strings.Join(parts, ", ") + "}"
}

// uint64s spells a bit set in hexadecimal, which is how a reader compares two.
func uint64s(values []uint64) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = "0x" + strconv.FormatUint(v, 16)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// quoted spells a string slice on one line.
func quoted(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}
