package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v3/internal/cmdutil"
	"github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"
)

// tablePath is the generated table the server compiles in.
const tablePath = "internal/tools/actiongrants/table_gen.go"

// tableHeader opens the file. The first line is the form Go's tools read as
// "generated", so linters and reviewers skip it.
const tableHeader = `// Code generated by cmd/gen_action_grants; DO NOT EDIT.

package actiongrants

import "github.com/jmrplens/gitlab-mcp-server/v3/internal/finegrained"

// table is what a fine-grained token needs for each catalog action at the
// GitLab release the live record was taken from: the join of the requests the
// handlers send (docs/development/action-requests.json) with the
// authorization GitLab declares for them (docs/development/gitlab-api-live.json).
// Every value is a constant, so the compiler lays it out as data and the
// binary runs no code to build it.
var table = finegrained.Table{
`

// boundaryConstants spells each boundary bit as the constant that names it,
// in the order finegrained.Boundary.Names reads them.
var boundaryConstants = map[string]string{
	"project":  "finegrained.BoundaryProject",
	"group":    "finegrained.BoundaryGroup",
	"user":     "finegrained.BoundaryUser",
	"instance": "finegrained.BoundaryInstance",
}

// renderTable writes the table as Go source of keyed composite literals, so a
// field added to a finegrained type leaves an older table compiling.
func renderTable(table *finegrained.Table) []byte {
	var b bytes.Buffer
	b.WriteString(tableHeader)
	fmt.Fprintf(&b, "Version: %q,\nBucket: %q,\n", table.Version, table.Bucket)
	writeStrings(&b, "Permissions", table.Permissions)
	writeStrings(&b, "Display", table.Display)
	writeStrings(&b, "RefusalDisplay", table.RefusalDisplay)
	b.WriteString("Assignables: []finegrained.Assignable{\n")
	for _, a := range table.Assignables {
		fmt.Fprintf(&b, "{Name: %q, Permissions: %s, Boundaries: %s", a.Name, uint16s(a.Permissions), boundary(a.Boundaries))
		writeFlag(&b, "Deprecated", a.Deprecated)
		writeFlag(&b, "Grantable", a.Grantable)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
	b.WriteString("PublicAnonymous: [2][]uint64{\n")
	for _, set := range table.PublicAnonymous {
		b.WriteString(uint64s(set) + ",\n")
	}
	b.WriteString("},\n")
	fmt.Fprintf(&b, "PublicKnown: %t,\n", table.PublicKnown)
	b.WriteString("Groups: []finegrained.Group{\n")
	for _, g := range table.Groups {
		fmt.Fprintf(&b, "{Perms: %s, Any: %s},\n", uint16s(g.Perms), boundary(g.Any))
	}
	b.WriteString("},\n")
	b.WriteString("Operations: []finegrained.Operation{\n")
	for _, op := range table.Operations {
		fmt.Fprintf(&b, "{Name: %q", op.Name)
		writeIndices(&b, "Groups", op.Groups)
		writeFlag(&b, "Skip", op.Skip)
		writeIndices(&b, "Spine", op.Spine)
		writeIndices(&b, "OffSpine", op.OffSpine)
		b.WriteString("},\n")
	}
	b.WriteString("},\n")
	b.WriteString("Elements: []finegrained.Element{\n")
	for _, e := range table.Elements {
		fmt.Fprintf(&b, "{Path: %q, Type: %q", e.Path, e.Type)
		if len(e.Members) > 0 {
			b.WriteString(", Members: " + quoted(e.Members))
		}
		writeIndices(&b, "Groups", e.Groups)
		writeFlag(&b, "Undeclared", e.Undeclared)
		fmt.Fprintf(&b, ", Effect: %q},\n", e.Effect)
	}
	b.WriteString("},\n")
	b.WriteString("Actions: []finegrained.Requirement{\n")
	for _, row := range table.Actions {
		fmt.Fprintf(&b, "{ID: %q", row.ID)
		if len(row.Paths) > 0 {
			paths := make([]string, len(row.Paths))
			for i, path := range row.Paths {
				paths[i] = uint32s(path)[len("[]uint32"):]
			}
			b.WriteString(", Paths: [][]uint32{" + strings.Join(paths, ", ") + "}")
		}
		if row.Denied != nil {
			fmt.Fprintf(&b, ", Denied: &finegrained.Denial%s", denial(*row.Denied))
		}
		if len(row.DeniedWays) > 0 {
			ways := make([]string, len(row.DeniedWays))
			for i, way := range row.DeniedWays {
				ways[i] = denial(way)
			}
			b.WriteString(", DeniedWays: []finegrained.Denial{" + strings.Join(ways, ", ") + "}")
		}
		writeIndices(&b, "Degraded", row.Degraded)
		writeFlag(&b, "GraphQL", row.GraphQL)
		writeFlag(&b, "Collection", row.Collection)
		b.WriteString("},\n")
	}
	b.WriteString("},\n}\n")
	// The source is assembled from fixed fragments and quoted values, so a
	// formatting failure is a defect of this function, which the repository's
	// rule says to state at the leaf.
	return cmdutil.Must(format.Source(b.Bytes()))
}

// denial spells one denial's fields as a keyed literal body.
func denial(d finegrained.Denial) string {
	return fmt.Sprintf("{Cause: %q, Element: %q, Effect: %q}", d.Cause, d.Element, d.Effect)
}

// writeStrings writes a string slice field, one value per line.
func writeStrings(b *bytes.Buffer, field string, values []string) {
	fmt.Fprintf(b, "%s: []string{\n", field)
	for _, v := range values {
		fmt.Fprintf(b, "%q,\n", v)
	}
	b.WriteString("},\n")
}

// writeIndices writes an index slice field when it holds anything.
func writeIndices(b *bytes.Buffer, field string, values []uint32) {
	if len(values) > 0 {
		fmt.Fprintf(b, ", %s: %s", field, uint32s(values))
	}
}

// writeFlag writes a boolean field when it is set.
func writeFlag(b *bytes.Buffer, field string, set bool) {
	if set {
		fmt.Fprintf(b, ", %s: true", field)
	}
}

// boundary spells a boundary set as an expression of the constants.
func boundary(set finegrained.Boundary) string {
	names := set.Names()
	if len(names) == 0 {
		return "0"
	}
	parts := make([]string, len(names))
	for i, name := range names {
		parts[i] = boundaryConstants[name]
	}
	return strings.Join(parts, " | ")
}

// uint16s spells an index slice.
func uint16s(values []uint16) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.FormatUint(uint64(v), 10)
	}
	return "[]uint16{" + strings.Join(parts, ", ") + "}"
}

// uint32s spells an index slice.
func uint32s(values []uint32) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.FormatUint(uint64(v), 10)
	}
	return "[]uint32{" + strings.Join(parts, ", ") + "}"
}

// uint64s spells a bit set in hexadecimal, which is how a reader compares two.
func uint64s(values []uint64) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = "0x" + strconv.FormatUint(v, 16)
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

// quoted spells a string slice on one line.
func quoted(values []string) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Quote(v)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}
