package main

// docAreaByPackage maps every catalog owner package to its GitLab API doc area
// (the path under doc/api/, without the .md suffix; subdirectory areas use "/").
//
// Packages whose endpoints have no single REST doc page (GraphQL-only surfaces,
// admin/template aggregates) are intentionally omitted so the auditor reports
// them as needing manual triage rather than grading them against a wrong page.
func init() {
	docAreaByPackage = map[string]string{
		// Free / general
		"accessrequests":          "access_requests",
		"accesstokens":            "project_access_tokens",
		"avatar":                  "avatar",
		"awardemoji":              "emoji_reactions",
		"badges":                  "project_badges",
		"boards":                  "boards",
		"branches":                "branches",
		"cilint":                  "lint",
		"civariables":             "project_level_variables",
		"commitdiscussions":       "discussions",
		"commits":                 "commits",
		"containerregistry":       "container_registry",
		"deploykeys":              "deploy_keys",
		"deploymentmergerequests": "deployments",
		"deployments":             "deployments",
		"deploytokens":            "deploy_tokens",
		"environments":            "environments",
		"events":                  "events",
		"featureflags":            "feature_flags",
		"ffuserlists":             "feature_flag_user_lists",
		"files":                   "repository_files",
		"freezeperiods":           "freeze_periods",
		"health":                  "metadata",
		"impersonationtokens":     "user_tokens",
		"instancevariables":       "instance_level_ci_variables",
		"integrations":            "project_integrations",
		"invites":                 "invitations",
		"issuediscussions":        "discussions",
		"issuelinks":              "issue_links",
		"issuenotes":              "notes",
		"issues":                  "issues",
		"issuestatistics":         "issues_statistics",
		"jobs":                    "jobs",
		"jobtokenscope":           "project_job_token_scopes",
		"keys":                    "keys",
		"labels":                  "labels",
		"markdown":                "markdown",
		"members":                 "project_members",
		"mergerequests":           "merge_requests",
		"milestones":              "milestones",
		"modelregistry":           "model_registry",
		"mrapprovalsettings":      "merge_request_approval_settings",
		"mrchanges":               "merge_requests",
		"mrcontextcommits":        "merge_request_context_commits",
		"mrdiscussions":           "discussions",
		"mrdraftnotes":            "draft_notes",
		"mrnotes":                 "notes",
		"namespaces":              "namespaces",
		"notifications":           "notification_settings",
		"packages":                "packages",
		"pages":                   "pages",
		"pipelines":               "pipelines",
		"pipelineschedules":       "pipeline_schedules",
		"pipelinetriggers":        "pipeline_triggers",
		"projectimportexport":     "project_import_export",
		"projectstatistics":       "project_statistics",
		"projectstoragemoves":     "project_repository_storage_moves",
		"projecttemplates":        "project_templates",
		"protectedpackages":       "project_packages_protection_rules",
		"releaselinks":            "releases/links",
		"releases":                "releases/_index",
		"repository":              "repositories",
		"repositorysubmodules":    "repository_submodules",
		"resourceevents":          "resource_label_events",
		"resourcegroups":          "resource_groups",
		"runnercontrollers":       "runner_controllers",
		"runnercontrollerscopes":  "runner_controllers",
		"runnercontrollertokens":  "runner_controller_tokens",
		"runners":                 "runners",
		"search":                  "search",
		"snippetdiscussions":      "discussions",
		"snippetnotes":            "notes",
		"snippets":                "snippets",
		"snippetstoragemoves":     "snippet_repository_storage_moves",
		"tags":                    "tags",
		"todos":                   "todos",
		"uploads":                 "project_markdown_uploads",
		"useremails":              "user_email_addresses",
		"usergpgkeys":             "user_keys",
		"users":                   "users",
		"wikis":                   "wikis",
		"projects":                "projects",
		"projectmirrors":          "remote_mirrors",

		// Group surfaces
		"groupanalytics":         "group_activity_analytics",
		"groupboards":            "group_boards",
		"groupepicboards":        "group_epic_boards",
		"groupimportexport":      "group_import_export",
		"groupiterations":        "group_iterations",
		"grouplabels":            "group_labels",
		"groupldap":              "group_ldap_links",
		"groupmarkdownuploads":   "group_markdown_uploads",
		"groupmembers":           "group_members",
		"groupmilestones":        "group_milestones",
		"groupprotectedbranches": "group_protected_branches",
		"groupprotectedenvs":     "group_protected_environments",
		"grouprelationsexport":   "group_relations_export",
		"groupreleases":          "group_releases",
		"groups":                 "groups",
		"groupsaml":              "saml",
		"groupscim":              "scim",
		"groupserviceaccounts":   "service_accounts",
		"groupsshcerts":          "group_ssh_certificates",
		"groupstoragemoves":      "group_repository_storage_moves",
		"groupvariables":         "group_level_variables",
		"groupwikis":             "group_wikis",
		"projectserviceaccounts": "service_accounts",
		"protectedenvs":          "protected_environments",

		// Enterprise (Premium / Ultimate) surfaces
		"attestations":         "attestations",
		"auditevents":          "audit_events",
		"compliancepolicy":     "compliance_policy_settings",
		"dependencies":         "dependencies",
		"enterpriseusers":      "group_enterprise_users",
		"epicissues":           "epic_issues",
		"epics":                "epics",
		"epicnotes":            "epics",
		"epicdiscussions":      "epics",
		"externalstatuschecks": "status_checks",
		"geo":                  "geo_sites",
		"memberroles":          "member_roles",
		"mergetrains":          "merge_trains",
		"mrapprovals":          "merge_request_approvals",
		"projectaliases":       "project_aliases",
		"projectiterations":    "iterations",
		"securityfindings":     "vulnerability_findings",
		"securitysettings":     "project_security_settings",
		"vulnerabilities":      "vulnerabilities",
	}
	_ = docAreaByPackage
}
