// Command gen_action_catalog_manifest generates the ActionSpec group builder
// manifest used by the catalog-first runtime.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/jmrplens/gitlab-mcp-server/v2/cmd/internal/auditshared"
	"github.com/jmrplens/gitlab-mcp-server/v2/internal/cmdutil"
)

const (
	defaultSourceDir  = "internal/tools"
	defaultOutputPath = "internal/tools/action_specs_manifest_gen.go"
)

// main parses CLI flags, walks the source directory for buildXxxActionSpecs
// functions, generates the manifest file (or verifies it in --check mode),
// and exits non-zero on failure.
//
// Run this command after adding, removing, or renaming a
// buildXxxActionSpecs function in internal/tools; CI enforces that the
// committed manifest stays in sync with the source.
//
// Usage:
//
//	go run ./cmd/gen_action_catalog_manifest/            # rewrite manifest
//	go run ./cmd/gen_action_catalog_manifest/ --check    # fail if stale
func main() {
	sourceDir := flag.String("source", defaultSourceDir, "directory containing action spec group builder source files")
	outputPath := flag.String("output", defaultOutputPath, "generated manifest path")
	check := flag.Bool("check", false, "verify generated manifest is up to date without writing")
	flag.Parse()

	root, err := cmdutil.RepositoryRoot(".")
	if err != nil {
		cmdutil.Fatalf("find repository root: %v", err)
	}
	builders, err := auditshared.DiscoverActionSpecGroupBuilders(filepath.Join(root, *sourceDir))
	if err != nil {
		cmdutil.Fatalf("discover action spec group builders: %v", err)
	}
	content, err := generateManifest(builders)
	if err != nil {
		cmdutil.Fatalf("generate manifest: %v", err)
	}
	targetPath := filepath.Join(root, *outputPath)
	if *check {
		if checkErr := checkManifest(targetPath, content); checkErr != nil {
			cmdutil.Fatalf("check manifest: %v", checkErr)
		}
		return
	}
	if writeErr := os.WriteFile(targetPath, content, 0o600); writeErr != nil {
		cmdutil.Fatalf("write %s: %v", targetPath, writeErr)
	}
}

func generateManifest(builders []string) ([]byte, error) {
	var buffer bytes.Buffer
	buffer.WriteString("// Code generated by cmd/gen_action_catalog_manifest; DO NOT EDIT.\n\n")
	buffer.WriteString("package tools\n\n")
	buffer.WriteString("func actionSpecGroupBuilders() []actionSpecGroupBuilder {\n")
	buffer.WriteString("\treturn []actionSpecGroupBuilder{\n")
	for _, builder := range builders {
		fmt.Fprintf(&buffer, "\t\t%s,\n", builder)
	}
	buffer.WriteString("\t}\n")
	buffer.WriteString("}\n")
	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated manifest: %w", err)
	}
	return formatted, nil
}

func checkManifest(path string, want []byte) error {
	got, err := os.ReadFile(path) // #nosec G304 -- path is resolved from the local repository root and points to the generated manifest.
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale; run go run ./cmd/gen_action_catalog_manifest/", path)
	}
	return nil
}
