// Code generated by cmd/gen_brand; DO NOT EDIT.

package toolutil

// svgBrand is the project mark — "the fan-out": one source node projecting
// three branch arcs, the canonical action catalog reaching its three tool
// surfaces. Original artwork for this project (no GitLab trademark
// geometry); the canonical vector lives in cmd/gen_brand and is scaled to
// this 24×24 currentColor variant for MCP clients. Regenerate with
// `make brand`, then refresh the WebP fallbacks with cmd/gen_icon_webp.
const svgBrand = `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M 6.75 12 C 12 12, 12 5.25, 17.2 5.25" fill="none" stroke="currentColor" stroke-width="1.31" stroke-linecap="round"/><path d="M 6.75 12 H 17.2" fill="none" stroke="currentColor" stroke-width="1.31" stroke-linecap="round"/><path d="M 6.75 12 C 12 12, 12 18.8, 17.2 18.8" fill="none" stroke="currentColor" stroke-width="1.31" stroke-linecap="round"/><circle cx="18.6" cy="5.25" r="1.31" fill="currentColor"/><circle cx="18.6" cy="12" r="1.31" fill="currentColor"/><circle cx="18.6" cy="18.8" r="1.31" fill="currentColor"/><circle cx="5.25" cy="12" r="1.88" fill="currentColor"/></svg>`
