package main

// language is one language the reference is written in: where its pages go,
// and every word the generator writes in it.
//
// The table headers of a language are held to the length of their English
// twins, and a translated table cell to the length of its header, so that a
// table measures the same in both languages (see the package comment). That
// is why the Spanish "Nivel" has an English "Tier" beside it only in a column
// whose cells are always longer, and why the column the English pages head
// "Mandatory" is not headed "Required".
type language struct {
	code string
	dir  string

	generatedNote string

	indexTitle       string
	indexLabel       string
	indexDescription string
	indexIntro       string
	indexTotals      string

	headingQuestions    string
	headingCall         string
	headingAvailability string
	headingActions      string

	callDynamic           string
	callMeta              string
	callIndividual        string
	callStandaloneSurface string

	servedEverywhere string
	servedIntro      string
	servedTier       string
	servedSplit      string
	scope            string
	scopeJoin        string
	capabilities     map[string]string
	readOnlyCount    string

	actionsIntro    string
	destructiveNote string
	paramTierNote   string

	columnAction     string
	columnTier       string
	columnIndividual string
	columnParameter  string
	columnType       string
	columnMandatory  string
	columnDesc       string
	yes              string
	no               string

	factMeta           string
	factMetaStandalone string
	factIndividual     string
	factNoIndividual   string
	factTier           string
	factDotcomOnly     string
	factBehavior       string
	readOnly           string
	writes             string
	destructive        string
	idempotent         string
	notIdempotent      string
	noParameters       string
	oneOf              string
	oneOfJoin          string
	oneOfAnd           string
}

// pagePath is where a page of this reference is linked from another page.
// It is the same in both languages: the site rewrites a Spanish page's links
// into its own locale.
const pagePath = "/gitlab-mcp-server/reference/tools/"

// languages are the languages the reference is written in, English first:
// English is what a list in another language is counted against.
var languages = []language{english, spanish}

//nolint:dupl // english and spanish are one table in two languages: the same fields in the same order is what makes them twins.
var english = language{
	code: "en",
	dir:  "site/src/content/docs/reference/tools",

	generatedNote: "{/*Generated by cmd/gen_tool_reference from the action catalog and cmd/gen_tool_reference/domains.json. Edit those, then run make gen-tool-reference.*/}",

	indexTitle:       "Tools by domain",
	indexLabel:       "Overview",
	indexDescription: "Every action of GitLab MCP Server by domain: its canonical ID, its meta-tool and individual tool, its tier, its annotations and its parameters.",
	indexIntro:       "One page per catalog group, each listing every action of the group with its canonical ID, the tools that reach it on each surface, the tier that serves it, its annotations and its parameters. The pages are generated from the catalog the server builds, so what they say about an action is what the server serves; only the overview and the sample questions of a page are written by hand.",
	indexTotals:      "On GitLab.com at Ultimate the catalog holds %d actions; a self-managed Ultimate instance serves %d, a Premium one %d and a Free one %d.",

	headingQuestions:    "Sample questions",
	headingCall:         "How to call it",
	headingAvailability: "Availability",
	headingActions:      "Actions",

	callDynamic:           "- **Dynamic**, the default surface: call `gitlab_execute_action` with `action` set to the action's ID, such as `%s`, and its parameters in `params`. `gitlab_find_action` finds an ID from a description of the task.",
	callMeta:              "- **Meta** (`GITLAB_MCP_TOOL_SURFACE=meta`): call `%s` with `action` set to the action's name, such as `%s`, and its parameters in `params`.",
	callIndividual:        "- **Individual** (`GITLAB_MCP_TOOL_SURFACE=individual`): call the action's own tool, such as `%s`, with its parameters as the arguments.",
	callStandaloneSurface: "- **Meta** and **individual** (`GITLAB_MCP_TOOL_SURFACE=meta` or `individual`): each action is a tool of its own, such as `%s`, under the same name on both surfaces, with its parameters as the arguments.",

	servedEverywhere: "Every tier serves the whole group, on self-managed instances and on GitLab.com alike.",
	servedIntro:      "How many of these actions an instance serves at each tier, out of a total of %d:",
	servedTier:       "- **%s**: %d",
	servedSplit:      "- **%s**: %d on a self-managed instance, %d on GitLab.com",
	scope:            "Listed only for a token that carries %s: the server removes the group from every surface for a token whose scopes it knows and that lacks it.",
	scopeJoin:        " and ",
	capabilities: map[string]string{
		"elicitation": "Needs a client that supports MCP [elicitation](/gitlab-mcp-server/capabilities/elicitation/), which each action asks its questions through.",
	},
	readOnlyCount: "Read-only actions: %d of %d, the ones a deployment in read-only mode keeps.",

	actionsIntro:    "The description of each action, and of each of its parameters, is the text the server serves for it on the default surface, quoted as served.",
	destructiveNote: "A destructive action runs only once confirmed: the dynamic surface needs `confirm: true` on `gitlab_execute_action`, and the other two take a `confirm` parameter or the client's prompt ([Destructive actions](/gitlab-mcp-server/operations/security/#destructive-actions)).",
	paramTierNote:   "A parameter followed by a tier in parentheses is served only from that tier on.",

	columnAction:     "Action",
	columnTier:       "Tier",
	columnIndividual: "Individual",
	columnParameter:  "Parameter",
	columnType:       "Type",
	columnMandatory:  "Mandatory",
	columnDesc:       "Description",
	yes:              "yes",
	no:               "no",

	factMeta:           "- **Meta-tool**: `%s`, action `%s`",
	factMetaStandalone: "- **Meta-tool**: `%s`, a tool of its own",
	factIndividual:     "- **Individual tool**: `%s`",
	factNoIndividual:   "- **Individual tool**: none, the individual surface does not serve this action",
	factTier:           "- **Tier**: %s",
	factDotcomOnly:     "%s, GitLab.com only",
	factBehavior:       "- **Behavior**: %s",
	readOnly:           "read-only",
	writes:             "writes",
	destructive:        "destructive (needs confirmation)",
	idempotent:         "idempotent",
	notIdempotent:      "not idempotent",
	noParameters:       "No parameters.",
	oneOf:              "Also needs at least one of: %s.",
	oneOfJoin:          "; ",
	oneOfAnd:           " and ",
}

//nolint:dupl // the Spanish twin of english; see there.
var spanish = language{
	code: "es",
	dir:  "site/src/content/docs/es/reference/tools",

	generatedNote: "{/*Generado por cmd/gen_tool_reference a partir del catálogo de acciones y de cmd/gen_tool_reference/domains.json. Edita esos y ejecuta make gen-tool-reference.*/}",

	indexTitle:       "Herramientas por dominio",
	indexLabel:       "Descripción general",
	indexDescription: "Cada acción de GitLab MCP Server por dominio: su ID canónico, su meta-herramienta y su herramienta individual, su nivel, sus anotaciones y sus parámetros.",
	indexIntro:       "Una página por grupo del catálogo, cada una con todas las acciones del grupo: su ID canónico, las herramientas que la alcanzan en cada superficie, el nivel que la sirve, sus anotaciones y sus parámetros. Las páginas se generan a partir del catálogo que construye el servidor, así que lo que dicen de una acción es lo que sirve el servidor; solo la descripción general y las preguntas de ejemplo de cada página están escritas a mano.",
	indexTotals:      "En GitLab.com con Ultimate el catálogo tiene %d acciones; una instancia autogestionada sirve %d con Ultimate, %d con Premium y %d con Free.",

	headingQuestions:    "Preguntas de ejemplo",
	headingCall:         "Cómo llamarlo",
	headingAvailability: "Disponibilidad",
	headingActions:      "Acciones",

	callDynamic:           "- **Dinámica**, la superficie predeterminada: llama a `gitlab_execute_action` con `action` igual al ID de la acción, como `%s`, y sus parámetros en `params`. `gitlab_find_action` encuentra un ID a partir de una descripción de la tarea.",
	callMeta:              "- **Meta** (`GITLAB_MCP_TOOL_SURFACE=meta`): llama a `%s` con `action` igual al nombre de la acción, como `%s`, y sus parámetros en `params`.",
	callIndividual:        "- **Individual** (`GITLAB_MCP_TOOL_SURFACE=individual`): llama a la herramienta propia de la acción, como `%s`, pasándole directamente sus parámetros.",
	callStandaloneSurface: "- **Meta** e **individual** (`GITLAB_MCP_TOOL_SURFACE=meta` o `individual`): cada acción es una herramienta propia, como `%s`, con el mismo nombre en las dos superficies, a la que se le pasan directamente sus parámetros.",

	servedEverywhere: "Todos los niveles sirven el grupo completo, tanto en instancias autogestionadas como en GitLab.com.",
	servedIntro:      "Cuántas de estas acciones sirve una instancia en cada nivel, de un total de %d:",
	servedTier:       "- **%s**: %d",
	servedSplit:      "- **%s**: %d en una instancia autogestionada, %d en GitLab.com",
	scope:            "Solo se lista para un token que tenga %s: el servidor quita el grupo de todas las superficies a un token cuyos ámbitos conoce y que no lo tiene.",
	scopeJoin:        " y ",
	capabilities: map[string]string{
		"elicitation": "Necesita un cliente que admita la [elicitación](/gitlab-mcp-server/capabilities/elicitation/) de MCP, por la que cada acción hace sus preguntas.",
	},
	readOnlyCount: "Acciones de solo lectura: %d de %d, las que conserva un despliegue en modo de solo lectura.",

	actionsIntro:    "La descripción de cada acción, y la de cada uno de sus parámetros, es el texto que sirve el servidor para ella en la superficie predeterminada, citado tal cual; por eso está en inglés.",
	destructiveNote: "Una acción destructiva solo se ejecuta una vez confirmada: la superficie dinámica necesita `confirm: true` en `gitlab_execute_action`, y las otras dos aceptan un parámetro `confirm` o la pregunta del cliente ([Acciones destructivas](/gitlab-mcp-server/operations/security/#acciones-destructivas)).",
	paramTierNote:   "Un parámetro seguido de un nivel entre paréntesis solo se sirve a partir de ese nivel.",

	columnAction:     "Acción",
	columnTier:       "Nivel",
	columnIndividual: "Individual",
	columnParameter:  "Parámetro",
	columnType:       "Tipo",
	columnMandatory:  "Requerido",
	columnDesc:       "Descripción",
	yes:              "sí",
	no:               "no",

	factMeta:           "- **Meta-herramienta**: `%s`, acción `%s`",
	factMetaStandalone: "- **Meta-herramienta**: `%s`, una herramienta propia",
	factIndividual:     "- **Herramienta individual**: `%s`",
	factNoIndividual:   "- **Herramienta individual**: ninguna, la superficie individual no sirve esta acción",
	factTier:           "- **Nivel**: %s",
	factDotcomOnly:     "%s, solo GitLab.com",
	factBehavior:       "- **Comportamiento**: %s",
	readOnly:           "solo lectura",
	writes:             "escribe",
	destructive:        "destructiva (necesita confirmación)",
	idempotent:         "idempotente",
	notIdempotent:      "no idempotente",
	noParameters:       "Sin parámetros.",
	oneOf:              "Además necesita al menos uno de estos: %s.",
	oneOfJoin:          "; ",
	oneOfAnd:           " y ",
}
