package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v2/internal/cmdutil"
)

const (
	// shardExt is what the recorder names its files. One shard per test
	// process, so a package binary never shares a file with another.
	shardExt = ".jsonl"

	// maxShardLine bounds one recorded line. The longest today is a GraphQL
	// row with a dozen variables at a few hundred bytes, and the default
	// scanner limit of 64 KiB would be enough, but a line silently dropped
	// for being long would look exactly like a request nobody makes.
	maxShardLine = 1 << 20

	// inventoryNote is the header the artifact carries, since JSON has no
	// comments and the file is long enough that a reader will meet a row
	// before any prose about it.
	inventoryNote = "Generated by `make gen-request-inventory`; do not edit. " +
		"Every request the unit suite issues through internal/testutil.NewTestClient, " +
		"one row per package, method and endpoint, with identifiers replaced by placeholders. " +
		"See cmd/gen_request_inventory for what a row is and what it is not."
)

// shardRecord is one line of a recorder shard.
//
// It repeats the shape of requestRecord in internal/testutil rather than
// sharing the type: that package embeds the pinned GraphQL schema and
// net/http/httptest, and a command importing it would carry both into a binary
// with no use for either. The JSON field names are the contract, and both
// declarations say so.
type shardRecord struct {
	Package string `json:"package"`
	// Test names the test that built the client. It is read and deliberately
	// not written: the committed inventory is about the requests this server
	// makes, so adding a test that reaches an endpoint already listed must not
	// change it. The shard keeps it so a row can still be traced back.
	Test      string   `json:"test"`
	Kind      string   `json:"kind"`
	Method    string   `json:"method"`
	Path      string   `json:"path"`
	Query     []string `json:"query,omitempty"`
	Operation string   `json:"operation,omitempty"`
	Variables []string `json:"variables,omitempty"`
}

// row is one endpoint one package was seen to call.
type row struct {
	Package string `json:"package"`
	Kind    string `json:"kind"`
	Method  string `json:"method"`
	Path    string `json:"path"`
	// Query and Variables are the union of every name seen on this endpoint,
	// not one call's set. Two calls that differ only in which optional filter
	// they pass are the same endpoint, and the union answers what this server
	// can send it.
	Query     []string `json:"query,omitempty"`
	Operation string   `json:"operation,omitempty"`
	Variables []string `json:"variables,omitempty"`
}

// inventory is the committed artifact.
type inventory struct {
	Note     string `json:"note"`
	Requests []row  `json:"requests"`
}

// rowKey identifies the row a record belongs to.
type rowKey struct {
	pkg       string
	kind      string
	method    string
	path      string
	operation string
}

// readShards reads every shard in dir.
//
// An empty directory is an error rather than an empty inventory: the shards
// are written by a suite run, so nothing there means the suite did not run
// with recording on, and writing the empty result would erase the artifact and
// call it a change.
func readShards(dir string) ([]shardRecord, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("read shard directory: %w", err)
	}

	var records []shardRecord
	shards := 0
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != shardExt {
			continue
		}
		shards++
		read, readErr := readShard(filepath.Join(dir, entry.Name()))
		if readErr != nil {
			return nil, readErr
		}
		records = append(records, read...)
	}
	if shards == 0 {
		return nil, fmt.Errorf("no %s shard in %s: run `make gen-request-inventory`, which records the suite before merging it", shardExt, dir)
	}
	return records, nil
}

// readShard reads one shard file.
func readShard(path string) ([]shardRecord, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open shard: %w", err)
	}
	defer func() { _ = file.Close() }()

	var records []shardRecord
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, bufio.MaxScanTokenSize), maxShardLine)
	line := 0
	for scanner.Scan() {
		line++
		text := strings.TrimSpace(scanner.Text())
		if text == "" {
			continue
		}
		var record shardRecord
		if unmarshalErr := json.Unmarshal([]byte(text), &record); unmarshalErr != nil {
			return nil, fmt.Errorf("parse %s line %d: %w", path, line, unmarshalErr)
		}
		records = append(records, record)
	}
	if scanErr := scanner.Err(); scanErr != nil {
		return nil, fmt.Errorf("read %s: %w", path, scanErr)
	}
	return records, nil
}

// merge folds the records into one row per package, method and endpoint.
func merge(records []shardRecord) []row {
	queries := map[rowKey]map[string]struct{}{}
	variables := map[rowKey]map[string]struct{}{}
	for _, record := range records {
		key := rowKey{
			pkg:       record.Package,
			kind:      record.Kind,
			method:    record.Method,
			path:      record.Path,
			operation: record.Operation,
		}
		if _, ok := queries[key]; !ok {
			queries[key] = map[string]struct{}{}
			variables[key] = map[string]struct{}{}
		}
		addAll(queries[key], record.Query)
		addAll(variables[key], record.Variables)
	}

	rows := make([]row, 0, len(queries))
	for key, query := range queries {
		rows = append(rows, row{
			Package:   key.pkg,
			Kind:      key.kind,
			Method:    key.method,
			Path:      key.path,
			Query:     sortedNames(query),
			Operation: key.operation,
			Variables: sortedNames(variables[key]),
		})
	}
	sort.Slice(rows, func(i, j int) bool { return less(rows[i], rows[j]) })
	return rows
}

// addAll adds every name to set.
func addAll(set map[string]struct{}, names []string) {
	for _, name := range names {
		set[name] = struct{}{}
	}
}

// sortedNames renders a name set as a sorted slice, or nil when it is empty so
// the field is omitted rather than written as an empty array.
func sortedNames(set map[string]struct{}) []string {
	if len(set) == 0 {
		return nil
	}
	return slices.Sorted(maps.Keys(set))
}

// less orders two rows. Every field of the key takes part, so the order is
// total and two runs over the same tree write the same bytes.
func less(a, b row) bool {
	left := []string{a.Package, a.Path, a.Method, a.Operation, a.Kind}
	right := []string{b.Package, b.Path, b.Method, b.Operation, b.Kind}
	for i := range left {
		if left[i] != right[i] {
			return left[i] < right[i]
		}
	}
	return false
}

// maxReportedDifferences bounds how many changed requests a stale-artifact
// failure lists. A handler that moved changes one or two rows, and a
// regenerated catalog can change hundreds, which nobody reads off a CI log.
const maxReportedDifferences = 10

// differences names the requests the committed artifact and the recording
// disagree about, as lines under the failure that reports the drift.
//
// A committed file that is not this format at all yields nothing to say, and
// the failure stands on its own: the artifact is stale either way, and the
// only difference is whether this can be precise about how.
func differences(committed []byte, rows []row) string {
	var previous inventory
	if json.Unmarshal(committed, &previous) != nil {
		return ""
	}
	var report strings.Builder
	writeDifferences(&report, "now issued and not in the committed inventory", onlyIn(rows, previous.Requests))
	writeDifferences(&report, "in the committed inventory and no longer issued", onlyIn(previous.Requests, rows))
	return report.String()
}

// onlyIn lists the rows of these that are not in those, as the lines a report
// prints. Both are already sorted, so the result is too.
func onlyIn(these, those []row) []string {
	other := make(map[string]struct{}, len(those))
	for _, r := range those {
		other[rowLine(r)] = struct{}{}
	}
	only := make([]string, 0)
	for _, r := range these {
		if line := rowLine(r); !mapHas(other, line) {
			only = append(only, line)
		}
	}
	return only
}

// mapHas reports membership, named so the loop above reads as prose.
func mapHas(set map[string]struct{}, key string) bool {
	_, ok := set[key]
	return ok
}

// rowLine renders one row as the single line a difference is reported on.
func rowLine(r row) string {
	line := r.Package + " " + r.Method + " " + r.Path
	if r.Operation != "" {
		line += " " + r.Operation
	}
	if len(r.Query) > 0 {
		line += " ?" + strings.Join(r.Query, ",")
	}
	if len(r.Variables) > 0 {
		line += " $" + strings.Join(r.Variables, ",")
	}
	return line
}

// writeDifferences appends one titled group of lines, capped, and nothing at
// all when the group is empty.
func writeDifferences(report *strings.Builder, title string, lines []string) {
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(report, "\n  %s (%d):", title, len(lines))
	for _, line := range lines[:min(len(lines), maxReportedDifferences)] {
		fmt.Fprintf(report, "\n    %s", line)
	}
	if len(lines) > maxReportedDifferences {
		fmt.Fprintf(report, "\n    and %d more", len(lines)-maxReportedDifferences)
	}
}

// render marshals the inventory, with the trailing newline a text file in this
// repository ends with.
//
// The marshal goes through [cmdutil.Must] because it cannot fail on a value
// this function just built out of strings, and a caller handed that error
// could only print it and stop, which is what the panic already does.
func render(rows []row) []byte {
	encoded := cmdutil.Must(json.MarshalIndent(inventory{Note: inventoryNote, Requests: rows}, "", "  "))
	return append(encoded, '\n')
}
