package tools

import (
	"fmt"
	"strings"
	"testing"

	gitlabclient "github.com/jmrplens/gitlab-mcp-server/internal/gitlab"
	"github.com/jmrplens/gitlab-mcp-server/internal/tools/actioncatalog"
	dynamictools "github.com/jmrplens/gitlab-mcp-server/internal/tools/dynamic"
)

const (
	expectedBaseDynamicCatalogActions         = 855
	expectedEnterpriseDynamicCatalogActions   = 1010
	expectedGitLabComEnterpriseCatalogActions = 1015
)

func TestActionCatalog_BaselineCountsDoNotRegress(t *testing.T) {
	testCases := []struct {
		name       string
		client     *gitlabclient.Client
		enterprise bool
		want       int
	}{
		{name: "base", want: expectedBaseDynamicCatalogActions},
		{name: "self-managed enterprise", enterprise: true, want: expectedEnterpriseDynamicCatalogActions},
		{name: "gitlab.com enterprise", client: newGitLabDotComClient(t), enterprise: true, want: expectedGitLabComEnterpriseCatalogActions},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			catalog := mustBuildDynamicActionCatalogForTest(t, tc.client, tc.enterprise)
			if got := catalog.CountActions(); got != tc.want {
				t.Fatalf("dynamic catalog action count = %d, want %d", got, tc.want)
			}
		})
	}
}

func TestActionSpecCoverage_AllCatalogRoutesClassified(t *testing.T) {
	catalog := mustBuildDynamicActionCatalogForTest(t, newGitLabDotComClient(t), true)
	missing := make([]actioncatalog.ActionID, 0)
	for _, action := range catalog.Actions() {
		if action.SpecBacked {
			continue
		}
		if _, ok := temporaryActionSpecMigrationAllowlist[action.ID]; ok {
			continue
		}
		missing = append(missing, action.ID)
	}
	if len(missing) > 0 {
		t.Fatalf("catalog actions must be spec-backed or explicitly allowlisted:\n%s", formatActionSpecMigrationAllowlist(missing))
	}
}

var temporaryActionSpecMigrationAllowlist = map[actioncatalog.ActionID]struct{}{
	"admin.alert_metric_image_delete":                {},
	"admin.alert_metric_image_list":                  {},
	"admin.alert_metric_image_update":                {},
	"admin.alert_metric_image_upload":                {},
	"admin.app_statistics_get":                       {},
	"admin.appearance_get":                           {},
	"admin.appearance_update":                        {},
	"admin.application_create":                       {},
	"admin.application_delete":                       {},
	"admin.application_list":                         {},
	"admin.broadcast_message_create":                 {},
	"admin.broadcast_message_delete":                 {},
	"admin.broadcast_message_get":                    {},
	"admin.broadcast_message_list":                   {},
	"admin.broadcast_message_update":                 {},
	"admin.bulk_import_cancel":                       {},
	"admin.bulk_import_entity_failures":              {},
	"admin.bulk_import_entity_get":                   {},
	"admin.bulk_import_entity_list":                  {},
	"admin.bulk_import_get":                          {},
	"admin.bulk_import_list":                         {},
	"admin.bulk_import_start":                        {},
	"admin.cluster_agent_delete":                     {},
	"admin.cluster_agent_get":                        {},
	"admin.cluster_agent_list":                       {},
	"admin.cluster_agent_register":                   {},
	"admin.cluster_agent_token_create":               {},
	"admin.cluster_agent_token_get":                  {},
	"admin.cluster_agent_token_list":                 {},
	"admin.cluster_agent_token_revoke":               {},
	"admin.custom_attr_delete":                       {},
	"admin.custom_attr_get":                          {},
	"admin.custom_attr_list":                         {},
	"admin.custom_attr_set":                          {},
	"admin.db_migration_mark":                        {},
	"admin.dependency_proxy_delete":                  {},
	"admin.error_tracking_create":                    {},
	"admin.error_tracking_delete":                    {},
	"admin.error_tracking_get_settings":              {},
	"admin.error_tracking_list":                      {},
	"admin.error_tracking_update_settings":           {},
	"admin.feature_delete":                           {},
	"admin.feature_list":                             {},
	"admin.feature_list_definitions":                 {},
	"admin.feature_set":                              {},
	"admin.import_bitbucket":                         {},
	"admin.import_bitbucket_server":                  {},
	"admin.import_cancel_github":                     {},
	"admin.import_gists":                             {},
	"admin.import_github":                            {},
	"admin.license_add":                              {},
	"admin.license_delete":                           {},
	"admin.license_get":                              {},
	"admin.metadata_get":                             {},
	"admin.plan_limits_change":                       {},
	"admin.plan_limits_get":                          {},
	"admin.secure_file_create":                       {},
	"admin.secure_file_delete":                       {},
	"admin.secure_file_get":                          {},
	"admin.secure_file_list":                         {},
	"admin.settings_get":                             {},
	"admin.settings_update":                          {},
	"admin.sidekiq_compound_metrics":                 {},
	"admin.sidekiq_job_stats":                        {},
	"admin.sidekiq_process_metrics":                  {},
	"admin.sidekiq_queue_metrics":                    {},
	"admin.system_hook_add":                          {},
	"admin.system_hook_delete":                       {},
	"admin.system_hook_get":                          {},
	"admin.system_hook_list":                         {},
	"admin.system_hook_test":                         {},
	"admin.terraform_state_delete":                   {},
	"admin.terraform_state_get":                      {},
	"admin.terraform_state_list":                     {},
	"admin.terraform_state_lock":                     {},
	"admin.terraform_state_unlock":                   {},
	"admin.terraform_version_delete":                 {},
	"admin.topic_create":                             {},
	"admin.topic_delete":                             {},
	"admin.topic_get":                                {},
	"admin.topic_list":                               {},
	"admin.topic_update":                             {},
	"admin.usage_data_metric_definitions":            {},
	"admin.usage_data_non_sql_metrics":               {},
	"admin.usage_data_queries":                       {},
	"admin.usage_data_service_ping":                  {},
	"admin.usage_data_track_event":                   {},
	"admin.usage_data_track_events":                  {},
	"analyze.ci_config":                              {},
	"analyze.deployment_history":                     {},
	"analyze.issue_scope":                            {},
	"analyze.issue_summary":                          {},
	"analyze.milestone_report":                       {},
	"analyze.mr_changes":                             {},
	"analyze.mr_review":                              {},
	"analyze.mr_security":                            {},
	"analyze.pipeline_failure":                       {},
	"analyze.release_notes":                          {},
	"analyze.technical_debt":                         {},
	"attestation.download":                           {},
	"attestation.list":                               {},
	"audit_event.get_group":                          {},
	"audit_event.get_instance":                       {},
	"audit_event.get_project":                        {},
	"audit_event.list_group":                         {},
	"audit_event.list_instance":                      {},
	"audit_event.list_project":                       {},
	"compliance_policy.get":                          {},
	"compliance_policy.update":                       {},
	"dependency.export_create":                       {},
	"dependency.export_download":                     {},
	"dependency.export_get":                          {},
	"dependency.list":                                {},
	"discover_project.resolve":                       {},
	"dora_metrics.group":                             {},
	"dora_metrics.project":                           {},
	"enterprise_user.delete":                         {},
	"enterprise_user.disable_2fa":                    {},
	"enterprise_user.get":                            {},
	"enterprise_user.list":                           {},
	"external_status_check.create_project":           {},
	"external_status_check.delete_project":           {},
	"external_status_check.list_project":             {},
	"external_status_check.list_project_checks":      {},
	"external_status_check.list_project_mr_checks":   {},
	"external_status_check.retry_project":            {},
	"external_status_check.set_project_mr_status":    {},
	"external_status_check.update_project":           {},
	"geo.create":                                     {},
	"geo.delete":                                     {},
	"geo.edit":                                       {},
	"geo.get":                                        {},
	"geo.get_status":                                 {},
	"geo.list":                                       {},
	"geo.list_status":                                {},
	"geo.repair":                                     {},
	"group.analytics_issues_count":                   {},
	"group.analytics_members_count":                  {},
	"group.analytics_mr_count":                       {},
	"group.archive":                                  {},
	"group.badge_add":                                {},
	"group.badge_delete":                             {},
	"group.badge_edit":                               {},
	"group.badge_get":                                {},
	"group.badge_list":                               {},
	"group.badge_preview":                            {},
	"group.create":                                   {},
	"group.credential_delete_ssh_key":                {},
	"group.credential_list_pats":                     {},
	"group.credential_list_ssh_keys":                 {},
	"group.credential_revoke_pat":                    {},
	"group.delete":                                   {},
	"group.epic_board_get":                           {},
	"group.epic_board_list":                          {},
	"group.epic_create":                              {},
	"group.epic_delete":                              {},
	"group.epic_discussion_add_note":                 {},
	"group.epic_discussion_create":                   {},
	"group.epic_discussion_delete_note":              {},
	"group.epic_discussion_get":                      {},
	"group.epic_discussion_list":                     {},
	"group.epic_discussion_update_note":              {},
	"group.epic_get":                                 {},
	"group.epic_get_links":                           {},
	"group.epic_issue_list":                          {},
	"group.epic_issue_remove":                        {},
	"group.epic_issue_update":                        {},
	"group.epic_list":                                {},
	"group.epic_note_create":                         {},
	"group.epic_note_delete":                         {},
	"group.epic_note_get":                            {},
	"group.epic_note_list":                           {},
	"group.epic_note_update":                         {},
	"group.epic_update":                              {},
	"group.get":                                      {},
	"group.group_board_create":                       {},
	"group.group_board_create_list":                  {},
	"group.group_board_delete":                       {},
	"group.group_board_delete_list":                  {},
	"group.group_board_get":                          {},
	"group.group_board_get_list":                     {},
	"group.group_board_list":                         {},
	"group.group_board_list_lists":                   {},
	"group.group_board_update":                       {},
	"group.group_board_update_list":                  {},
	"group.group_export_download":                    {},
	"group.group_export_schedule":                    {},
	"group.group_import_file":                        {},
	"group.group_label_create":                       {},
	"group.group_label_delete":                       {},
	"group.group_label_get":                          {},
	"group.group_label_list":                         {},
	"group.group_label_subscribe":                    {},
	"group.group_label_unsubscribe":                  {},
	"group.group_label_update":                       {},
	"group.group_member_add":                         {},
	"group.group_member_edit":                        {},
	"group.group_member_get":                         {},
	"group.group_member_get_inherited":               {},
	"group.group_member_remove":                      {},
	"group.group_member_share":                       {},
	"group.group_member_unshare":                     {},
	"group.group_milestone_burndown":                 {},
	"group.group_milestone_create":                   {},
	"group.group_milestone_delete":                   {},
	"group.group_milestone_get":                      {},
	"group.group_milestone_issues":                   {},
	"group.group_milestone_list":                     {},
	"group.group_milestone_merge_requests":           {},
	"group.group_milestone_update":                   {},
	"group.group_relations_list_status":              {},
	"group.group_relations_schedule":                 {},
	"group.group_upload_delete_by_id":                {},
	"group.group_upload_delete_by_secret":            {},
	"group.group_upload_list":                        {},
	"group.hook_add":                                 {},
	"group.hook_delete":                              {},
	"group.hook_edit":                                {},
	"group.hook_get":                                 {},
	"group.hook_list":                                {},
	"group.issues":                                   {},
	"group.ldap_link_add":                            {},
	"group.ldap_link_delete":                         {},
	"group.ldap_link_delete_for_provider":            {},
	"group.ldap_link_list":                           {},
	"group.list":                                     {},
	"group.members":                                  {},
	"group.projects":                                 {},
	"group.protected_branch_get":                     {},
	"group.protected_branch_list":                    {},
	"group.protected_branch_protect":                 {},
	"group.protected_branch_unprotect":               {},
	"group.protected_branch_update":                  {},
	"group.protected_env_get":                        {},
	"group.protected_env_list":                       {},
	"group.protected_env_protect":                    {},
	"group.protected_env_unprotect":                  {},
	"group.protected_env_update":                     {},
	"group.release_list":                             {},
	"group.restore":                                  {},
	"group.saml_link_add":                            {},
	"group.saml_link_delete":                         {},
	"group.saml_link_get":                            {},
	"group.saml_link_list":                           {},
	"group.search":                                   {},
	"group.security_settings_update":                 {},
	"group.service_account_create":                   {},
	"group.service_account_delete":                   {},
	"group.service_account_list":                     {},
	"group.service_account_pat_create":               {},
	"group.service_account_pat_list":                 {},
	"group.service_account_pat_revoke":               {},
	"group.service_account_update":                   {},
	"group.ssh_cert_create":                          {},
	"group.ssh_cert_delete":                          {},
	"group.ssh_cert_list":                            {},
	"group.subgroups":                                {},
	"group.transfer_project":                         {},
	"group.unarchive":                                {},
	"group.update":                                   {},
	"group.wiki_create":                              {},
	"group.wiki_delete":                              {},
	"group.wiki_edit":                                {},
	"group.wiki_get":                                 {},
	"group.wiki_list":                                {},
	"group_scim.delete":                              {},
	"group_scim.get":                                 {},
	"group_scim.list":                                {},
	"group_scim.update":                              {},
	"interactive.issue_create":                       {},
	"interactive.mr_create":                          {},
	"interactive.project_create":                     {},
	"interactive.release_create":                     {},
	"issue.create":                                   {},
	"issue.create_todo":                              {},
	"issue.delete":                                   {},
	"issue.discussion_add_note":                      {},
	"issue.discussion_create":                        {},
	"issue.discussion_delete_note":                   {},
	"issue.discussion_get":                           {},
	"issue.discussion_list":                          {},
	"issue.discussion_update_note":                   {},
	"issue.emoji_issue_create":                       {},
	"issue.emoji_issue_delete":                       {},
	"issue.emoji_issue_get":                          {},
	"issue.emoji_issue_list":                         {},
	"issue.emoji_issue_note_create":                  {},
	"issue.emoji_issue_note_delete":                  {},
	"issue.emoji_issue_note_get":                     {},
	"issue.emoji_issue_note_list":                    {},
	"issue.event_issue_iteration_get":                {},
	"issue.event_issue_iteration_list":               {},
	"issue.event_issue_label_get":                    {},
	"issue.event_issue_label_list":                   {},
	"issue.event_issue_milestone_get":                {},
	"issue.event_issue_milestone_list":               {},
	"issue.event_issue_state_get":                    {},
	"issue.event_issue_state_list":                   {},
	"issue.event_issue_weight_list":                  {},
	"issue.get":                                      {},
	"issue.get_by_id":                                {},
	"issue.iteration_list_group":                     {},
	"issue.iteration_list_project":                   {},
	"issue.link_delete":                              {},
	"issue.link_get":                                 {},
	"issue.link_list":                                {},
	"issue.list":                                     {},
	"issue.list_all":                                 {},
	"issue.list_group":                               {},
	"issue.move":                                     {},
	"issue.mrs_closing":                              {},
	"issue.mrs_related":                              {},
	"issue.note_create":                              {},
	"issue.note_delete":                              {},
	"issue.note_get":                                 {},
	"issue.note_list":                                {},
	"issue.note_update":                              {},
	"issue.participants":                             {},
	"issue.reorder":                                  {},
	"issue.spent_time_add":                           {},
	"issue.spent_time_reset":                         {},
	"issue.statistics_get":                           {},
	"issue.statistics_get_group":                     {},
	"issue.statistics_get_project":                   {},
	"issue.subscribe":                                {},
	"issue.time_estimate_reset":                      {},
	"issue.time_estimate_set":                        {},
	"issue.time_stats_get":                           {},
	"issue.unsubscribe":                              {},
	"issue.update":                                   {},
	"issue.work_item_create":                         {},
	"issue.work_item_delete":                         {},
	"issue.work_item_get":                            {},
	"issue.work_item_list":                           {},
	"issue.work_item_update":                         {},
	"member_role.create_group":                       {},
	"member_role.create_instance":                    {},
	"member_role.delete_group":                       {},
	"member_role.delete_instance":                    {},
	"member_role.list_group":                         {},
	"member_role.list_instance":                      {},
	"merge_request.approval_config":                  {},
	"merge_request.approval_reset":                   {},
	"merge_request.approval_rule_create":             {},
	"merge_request.approval_rule_delete":             {},
	"merge_request.approval_rule_update":             {},
	"merge_request.approval_rules":                   {},
	"merge_request.approval_settings_group_get":      {},
	"merge_request.approval_settings_group_update":   {},
	"merge_request.approval_settings_project_get":    {},
	"merge_request.approval_settings_project_update": {},
	"merge_request.approval_state":                   {},
	"merge_request.approve":                          {},
	"merge_request.cancel_auto_merge":                {},
	"merge_request.commits":                          {},
	"merge_request.context_commits_create":           {},
	"merge_request.context_commits_delete":           {},
	"merge_request.context_commits_list":             {},
	"merge_request.create_pipeline":                  {},
	"merge_request.create_todo":                      {},
	"merge_request.delete":                           {},
	"merge_request.dependencies_list":                {},
	"merge_request.dependency_create":                {},
	"merge_request.dependency_delete":                {},
	"merge_request.emoji_mr_create":                  {},
	"merge_request.emoji_mr_delete":                  {},
	"merge_request.emoji_mr_get":                     {},
	"merge_request.emoji_mr_list":                    {},
	"merge_request.emoji_mr_note_create":             {},
	"merge_request.emoji_mr_note_delete":             {},
	"merge_request.emoji_mr_note_get":                {},
	"merge_request.emoji_mr_note_list":               {},
	"merge_request.event_mr_label_get":               {},
	"merge_request.event_mr_label_list":              {},
	"merge_request.event_mr_milestone_get":           {},
	"merge_request.event_mr_milestone_list":          {},
	"merge_request.event_mr_state_get":               {},
	"merge_request.event_mr_state_list":              {},
	"merge_request.get":                              {},
	"merge_request.issues_closed":                    {},
	"merge_request.list":                             {},
	"merge_request.list_global":                      {},
	"merge_request.list_group":                       {},
	"merge_request.merge":                            {},
	"merge_request.participants":                     {},
	"merge_request.pipelines":                        {},
	"merge_request.rebase":                           {},
	"merge_request.related_issues":                   {},
	"merge_request.reviewers":                        {},
	"merge_request.spent_time_add":                   {},
	"merge_request.spent_time_reset":                 {},
	"merge_request.subscribe":                        {},
	"merge_request.time_estimate_reset":              {},
	"merge_request.time_estimate_set":                {},
	"merge_request.time_stats":                       {},
	"merge_request.unapprove":                        {},
	"merge_request.unsubscribe":                      {},
	"merge_request.update":                           {},
	"merge_train.add":                                {},
	"merge_train.get":                                {},
	"merge_train.list_branch":                        {},
	"merge_train.list_project":                       {},
	"orbit.graph_status":                             {},
	"orbit.query":                                    {},
	"orbit.schema":                                   {},
	"orbit.status":                                   {},
	"orbit.tools":                                    {},
	"project_alias.create":                           {},
	"project_alias.delete":                           {},
	"project_alias.get":                              {},
	"project_alias.list":                             {},
	"runner.controller_create":                       {},
	"runner.controller_delete":                       {},
	"runner.controller_get":                          {},
	"runner.controller_list":                         {},
	"runner.controller_scope_add_instance":           {},
	"runner.controller_scope_add_runner":             {},
	"runner.controller_scope_list":                   {},
	"runner.controller_scope_remove_instance":        {},
	"runner.controller_scope_remove_runner":          {},
	"runner.controller_token_create":                 {},
	"runner.controller_token_get":                    {},
	"runner.controller_token_list":                   {},
	"runner.controller_token_revoke":                 {},
	"runner.controller_token_rotate":                 {},
	"runner.controller_update":                       {},
	"runner.delete_by_token":                         {},
	"runner.delete_registered":                       {},
	"runner.disable_project":                         {},
	"runner.enable_project":                          {},
	"runner.get":                                     {},
	"runner.jobs":                                    {},
	"runner.list":                                    {},
	"runner.list_all":                                {},
	"runner.list_group":                              {},
	"runner.list_managers":                           {},
	"runner.list_project":                            {},
	"runner.register":                                {},
	"runner.remove":                                  {},
	"runner.reset_group_reg_token":                   {},
	"runner.reset_instance_reg_token":                {},
	"runner.reset_project_reg_token":                 {},
	"runner.reset_token":                             {},
	"runner.update":                                  {},
	"runner.verify":                                  {},
	"security_finding.list":                          {},
	"server.health_check":                            {},
	"server.status":                                  {},
	"storage_move.get_group":                         {},
	"storage_move.get_group_for_group":               {},
	"storage_move.get_project":                       {},
	"storage_move.get_project_for_project":           {},
	"storage_move.get_snippet":                       {},
	"storage_move.get_snippet_for_snippet":           {},
	"storage_move.retrieve_all_group":                {},
	"storage_move.retrieve_all_project":              {},
	"storage_move.retrieve_all_snippet":              {},
	"storage_move.retrieve_group":                    {},
	"storage_move.retrieve_project":                  {},
	"storage_move.retrieve_snippet":                  {},
	"storage_move.schedule_all_group":                {},
	"storage_move.schedule_all_project":              {},
	"storage_move.schedule_all_snippet":              {},
	"storage_move.schedule_group":                    {},
	"storage_move.schedule_project":                  {},
	"storage_move.schedule_snippet":                  {},
	"user.activate":                                  {},
	"user.activities":                                {},
	"user.add_email":                                 {},
	"user.add_email_for_user":                        {},
	"user.add_gpg_key":                               {},
	"user.add_gpg_key_for_user":                      {},
	"user.add_ssh_key":                               {},
	"user.add_ssh_key_for_user":                      {},
	"user.approve":                                   {},
	"user.associations_count":                        {},
	"user.avatar_get":                                {},
	"user.ban":                                       {},
	"user.block":                                     {},
	"user.contribution_events":                       {},
	"user.create":                                    {},
	"user.create_current_user_pat":                   {},
	"user.create_impersonation_token":                {},
	"user.create_personal_access_token":              {},
	"user.create_runner":                             {},
	"user.create_service_account":                    {},
	"user.current":                                   {},
	"user.current_user_status":                       {},
	"user.deactivate":                                {},
	"user.delete":                                    {},
	"user.delete_email":                              {},
	"user.delete_email_for_user":                     {},
	"user.delete_gpg_key":                            {},
	"user.delete_gpg_key_for_user":                   {},
	"user.delete_identity":                           {},
	"user.delete_ssh_key":                            {},
	"user.delete_ssh_key_for_user":                   {},
	"user.disable_two_factor":                        {},
	"user.emails":                                    {},
	"user.emails_for_user":                           {},
	"user.event_list_contributions":                  {},
	"user.event_list_project":                        {},
	"user.get":                                       {},
	"user.get_email":                                 {},
	"user.get_gpg_key":                               {},
	"user.get_gpg_key_for_user":                      {},
	"user.get_impersonation_token":                   {},
	"user.get_ssh_key":                               {},
	"user.get_ssh_key_for_user":                      {},
	"user.get_status":                                {},
	"user.gpg_keys":                                  {},
	"user.gpg_keys_for_user":                         {},
	"user.key_get_by_fingerprint":                    {},
	"user.key_get_with_user":                         {},
	"user.list":                                      {},
	"user.list_impersonation_tokens":                 {},
	"user.list_service_accounts":                     {},
	"user.me":                                        {},
	"user.memberships":                               {},
	"user.modify":                                    {},
	"user.namespace_exists":                          {},
	"user.namespace_get":                             {},
	"user.namespace_list":                            {},
	"user.namespace_search":                          {},
	"user.notification_global_get":                   {},
	"user.notification_global_update":                {},
	"user.notification_group_get":                    {},
	"user.notification_group_update":                 {},
	"user.notification_project_get":                  {},
	"user.notification_project_update":               {},
	"user.reject":                                    {},
	"user.revoke_impersonation_token":                {},
	"user.set_status":                                {},
	"user.ssh_keys":                                  {},
	"user.ssh_keys_for_user":                         {},
	"user.todo_list":                                 {},
	"user.todo_mark_all_done":                        {},
	"user.todo_mark_done":                            {},
	"user.unban":                                     {},
	"user.unblock":                                   {},
	"vulnerability.confirm":                          {},
	"vulnerability.dismiss":                          {},
	"vulnerability.get":                              {},
	"vulnerability.list":                             {},
	"vulnerability.pipeline_security_summary":        {},
	"vulnerability.resolve":                          {},
	"vulnerability.revert":                           {},
	"vulnerability.severity_count":                   {},
}

func mustBuildDynamicActionCatalogForTest(t *testing.T, client *gitlabclient.Client, enterprise bool) *actioncatalog.Catalog {
	t.Helper()
	catalog := mustBuildActionCatalog(t, client, ActionCatalogOptions{Enterprise: enterprise, IncludeMCP: true})
	catalog, err := dynamictools.AddStandaloneCatalog(catalog, client, dynamictools.StandaloneOptions{})
	if err != nil {
		t.Fatalf("AddStandaloneCatalog() error = %v", err)
	}
	return catalog
}

func formatActionSpecMigrationAllowlist(ids []actioncatalog.ActionID) string {
	var builder strings.Builder
	for _, id := range ids {
		fmt.Fprintf(&builder, "\t%q: {},\n", id)
	}
	return builder.String()
}
