package requestinventory

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jmrplens/gitlab-mcp-server/v2/internal/cmdutil"
)

const (
	// Path is where the committed artifact lives, relative to the repository
	// root.
	Path = "docs/development/request-inventory.json"

	// Note is the header the artifact carries, since JSON has no comments and
	// the file is long enough that a reader will meet a row before any prose
	// about it.
	Note = "Generated by `make gen-request-inventory`; do not edit. " +
		"Every request the unit suite issues through internal/testutil.NewTestClient, " +
		"one row per package, method and endpoint, with identifiers replaced by placeholders. " +
		"See cmd/gen_request_inventory for what a row is and what it is not."

	// KindREST and KindGraphQL are the two shapes a row comes in.
	KindREST    = "rest"
	KindGraphQL = "graphql"
)

// Row is one endpoint one package was seen to call.
type Row struct {
	Package string `json:"package"`
	Kind    string `json:"kind"`
	Method  string `json:"method"`
	Path    string `json:"path"`
	// Query and Variables are the union of every name seen on this endpoint,
	// not one call's set. Two calls that differ only in which optional filter
	// they pass are the same endpoint, and the union answers what this server
	// can send it.
	Query     []string `json:"query,omitempty"`
	Operation string   `json:"operation,omitempty"`
	Variables []string `json:"variables,omitempty"`
}

// Inventory is the committed artifact.
type Inventory struct {
	Note     string `json:"note"`
	Requests []Row  `json:"requests"`
}

// Read loads the committed inventory from a repository root.
//
// An artifact with no rows in it is an error rather than an empty inventory:
// every caller here answers a question of the form "which of these did the
// suite never issue", and an empty file answers all of them with "none of
// them", which is the loudest possible wrong answer.
func Read(root string) (Inventory, error) {
	target := filepath.Join(root, filepath.FromSlash(Path))
	content, err := os.ReadFile(target) //#nosec G304 -- the path is derived from the repository root
	if err != nil {
		return Inventory{}, fmt.Errorf("read the request inventory: %w", err)
	}
	var inventory Inventory
	if unmarshalErr := json.Unmarshal(content, &inventory); unmarshalErr != nil {
		return Inventory{}, fmt.Errorf("parse %s: %w", Path, unmarshalErr)
	}
	if len(inventory.Requests) == 0 {
		return Inventory{}, fmt.Errorf("%s holds no request: run `make gen-request-inventory`", Path)
	}
	return inventory, nil
}

// Render marshals rows as the committed artifact, with the trailing newline a
// text file in this repository ends with.
//
// The marshal goes through [cmdutil.Must] because it cannot fail on a value
// built out of strings, and a caller handed that error could only print it and
// stop, which is what the panic already does.
func Render(rows []Row) []byte {
	encoded := cmdutil.Must(json.MarshalIndent(Inventory{Note: Note, Requests: rows}, "", "  "))
	return append(encoded, '\n')
}
