package requestinventory

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jmrplens/gitlab-mcp-server/v2/internal/cmdutil"
)

const (
	// Path is where the committed artifact lives, relative to the repository
	// root.
	Path = "docs/development/request-inventory.json"

	// Note is the header the artifact carries, since JSON has no comments and
	// the file is long enough that a reader will meet a row before any prose
	// about it.
	Note = "Generated by `make gen-request-inventory`; do not edit. " +
		"One row per package, method and templated endpoint: what the unit suite was seen to send " +
		"through internal/testutil.NewTestClient, which is not the same as everything this server can send. " +
		"`query`, `body` and `variables` are the union of the names that package sent that endpoint, never one call's set. " +
		"A segment the shape rule could not recognize as an identifier is still a fixture value, " +
		"so one endpoint reached with two branch names is two rows: the rule is in internal/testutil/request_shape.go " +
		"and what a row is is in cmd/internal/requestinventory. " +
		"Recorded on Linux; a run on another platform may legitimately skip a test and record less."

	// KindREST and KindGraphQL are the two shapes a row comes in.
	KindREST    = "rest"
	KindGraphQL = "graphql"
)

// Row is one endpoint one package was seen to call.
type Row struct {
	Package string `json:"package"`
	Kind    string `json:"kind"`
	Method  string `json:"method"`
	Path    string `json:"path"`
	// Query, Body and Variables are the union of every name this package was
	// seen sending this endpoint, never one call's set. Two calls that differ
	// only in which optional filter they pass are the same endpoint, so the
	// union answers which names were sent it and deliberately not which of
	// them were sent together: a combination is a property of the tests, and
	// reading one off this file would be reading a fixture as a contract.
	Query     []string `json:"query,omitempty"`
	Body      []string `json:"body,omitempty"`
	Operation string   `json:"operation,omitempty"`
	Variables []string `json:"variables,omitempty"`
}

// Inventory is the committed artifact.
type Inventory struct {
	Note     string `json:"note"`
	Requests []Row  `json:"requests"`
}

// Read loads the committed inventory from a repository root.
//
// An artifact with no rows in it is an error rather than an empty inventory:
// every caller here answers a question of the form "which of these did the
// suite never issue", and an empty file answers all of them with "none of
// them", which is the loudest possible wrong answer.
func Read(root string) (Inventory, error) {
	target := filepath.Join(root, filepath.FromSlash(Path))
	content, err := os.ReadFile(target) //#nosec G304 -- the path is derived from the repository root
	if err != nil {
		return Inventory{}, fmt.Errorf("read the request inventory: %w", err)
	}
	var inventory Inventory
	if unmarshalErr := json.Unmarshal(content, &inventory); unmarshalErr != nil {
		return Inventory{}, fmt.Errorf("parse %s: %w", Path, unmarshalErr)
	}
	if len(inventory.Requests) == 0 {
		return Inventory{}, fmt.Errorf("%s holds no request: run `make gen-request-inventory`", Path)
	}
	return inventory, nil
}

// Render marshals rows as the committed artifact, with the trailing newline a
// text file in this repository ends with.
//
// The marshal goes through [cmdutil.Must] because it cannot fail on a value
// built out of strings, and a caller handed that error could only print it and
// stop, which is what the panic already does.
func Render(rows []Row) []byte {
	encoded := cmdutil.Must(json.MarshalIndent(Inventory{Note: Note, Requests: rows}, "", "  "))
	return append(encoded, '\n')
}
