#!/usr/bin/env bash
# Regenerate the Homebrew tap formula (jmrplens/homebrew-tap) for a release.
#
# Renders Formula/gitlab-mcp-server.rb from the release version and the
# per-platform SHA256 hashes in GoReleaser's checksums.txt, then commits and
# pushes it to the tap repository. The caller must have push access to the
# tap (in CI: an SSH deploy key wired through GIT_SSH_COMMAND).
#
# Usage: update-homebrew-tap.sh <checksums-file> <version> [tap-clone-dir]

set -euo pipefail

CHECKSUMS_FILE="${1:?Usage: $0 <checksums-file> <version> [tap-clone-dir]}"
VERSION="${2:?Usage: $0 <checksums-file> <version> [tap-clone-dir]}"
TAP_DIR="${3:-homebrew-tap}"
TAP_REPO="${TAP_REPO:-git@github.com:jmrplens/homebrew-tap.git}"
BASE_URL="https://github.com/jmrplens/gitlab-mcp-server/releases/download/v${VERSION}"

sha_for() {
  local name="$1" sha
  sha=$(awk -v n="$name" '$2 == n {print $1}' "$CHECKSUMS_FILE")
  if [[ -z "$sha" ]]; then
    echo "ERROR: no checksum for $name in $CHECKSUMS_FILE" >&2
    exit 1
  fi
  echo "$sha"
}

SHA_DARWIN_ARM=$(sha_for gitlab-mcp-server-darwin-arm64)
SHA_DARWIN_INTEL=$(sha_for gitlab-mcp-server-darwin-amd64)
SHA_LINUX_ARM=$(sha_for gitlab-mcp-server-linux-arm64)
SHA_LINUX_INTEL=$(sha_for gitlab-mcp-server-linux-amd64)

if [[ ! -d "$TAP_DIR/.git" ]]; then
  git clone --depth 1 "$TAP_REPO" "$TAP_DIR"
fi

mkdir -p "$TAP_DIR/Formula"
cat > "$TAP_DIR/Formula/gitlab-mcp-server.rb" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by the release workflow of
# https://github.com/jmrplens/gitlab-mcp-server — do not edit by hand.
class GitlabMcpServer < Formula
  desc "GitLab MCP server: REST v4 + GraphQL as tools for AI assistants"
  homepage "https://jmrp.io/docs/gitlab-mcp-server"
  version "${VERSION}"
  license "MIT"

  livecheck do
    url "https://github.com/jmrplens/gitlab-mcp-server"
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "${BASE_URL}/gitlab-mcp-server-darwin-arm64"
      sha256 "${SHA_DARWIN_ARM}"
    end
    on_intel do
      url "${BASE_URL}/gitlab-mcp-server-darwin-amd64"
      sha256 "${SHA_DARWIN_INTEL}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/gitlab-mcp-server-linux-arm64"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "${BASE_URL}/gitlab-mcp-server-linux-amd64"
      sha256 "${SHA_LINUX_INTEL}"
    end
  end

  def install
    bin.install Dir["gitlab-mcp-server-*"].first => "gitlab-mcp-server"
  end

  def caveats
    <<~EOS
      Homebrew manages upgrades for this binary.

      Configure your MCP client with:
        command: #{HOMEBREW_PREFIX}/bin/gitlab-mcp-server
        env:     GITLAB_TOKEN=glpat-... (and GITLAB_URL for self-managed)

      Per-client JSON:
        https://jmrp.io/docs/gitlab-mcp-server/guides/ide-configuration/
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gitlab-mcp-server --version")
  end
end
EOF

cd "$TAP_DIR"
ruby -c Formula/gitlab-mcp-server.rb > /dev/null

git config user.name "José M. Requena Plens"
git config user.email "jmrplens@gmail.com"
git add Formula/gitlab-mcp-server.rb

if git diff --cached --quiet; then
  echo "Tap formula already up to date for v${VERSION}"
  exit 0
fi

git commit -m "gitlab-mcp-server ${VERSION}"
git push origin HEAD:main
echo "Tap formula updated to v${VERSION}"
