package actionrequests

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/jmrplens/gitlab-mcp-server/v3/internal/cmdutil"
)

// The committed record of what each catalog action sends GitLab. One writer
// produces it, cmd/gen_action_grants, from the handlers this package resolves;
// R-GRANT (cmd/audit_1to1 -scope=grants) reads it back to say what shaped each
// action's requirement and to hold the derivation to what the unit suite and
// an end-to-end run were seen sending. The shape is declared here, once, so
// the two cannot read the same file two ways.

// RecordPath is where the record lives, relative to the repository root.
const RecordPath = "docs/development/action-requests.json"

// RecordNote heads the record, so a reader arriving at the file knows what it
// is and where it comes from.
const RecordNote = "Generated by cmd/gen_action_grants from the handlers (make gen-action-grants); do not edit. " +
	"Per catalog action, the REST routes, in the live GitLab record's spelling, and the GraphQL operations its " +
	"handler can send, each classified by the paths that make it: mandatory on every path, an alternative on some, " +
	"optional on none. Where a request comes from is named by symbol, never by line, so a change to a handler shows " +
	"here as a change to what it sends."

// The kinds a recorded request comes in, and the classes it is needed by.
const (
	// KindREST is a REST route.
	KindREST = "rest"
	// KindGraphQL is one GraphQL document posted to the GraphQL endpoint.
	KindGraphQL = "graphql"
	// KindUnresolved is a request the walk reached and could not read, which a
	// declaration answers.
	KindUnresolved = "unresolved"

	// ClassMandatory is a request every path of the action makes.
	ClassMandatory = "mandatory"
	// ClassAlternative is a request some paths make and others do not.
	ClassAlternative = "alternative"
	// ClassOptional is a request no path needs.
	ClassOptional = "optional"
)

// Record is the file.
type Record struct {
	Note    string         `json:"note"`
	Actions []RecordAction `json:"actions"`
}

// RecordAction is one action.
type RecordAction struct {
	ID       string   `json:"id"`
	Handlers []string `json:"handlers"`
	// Declaration is the category of the action-level declaration that
	// answers what the walk could not, when one does.
	Declaration string          `json:"declaration,omitempty"`
	Requests    []RecordRequest `json:"requests,omitempty"`
	// Paths are the ways the action runs, as indices into Requests.
	Paths [][]int `json:"paths"`
}

// RecordRequest is one request of one action.
type RecordRequest struct {
	// Kind is one of the Kind constants.
	Kind string `json:"kind"`
	// Route is a REST request's route as the live record spells it, and
	// Derived the derivation's spelling where a declaration placed it.
	Route   string `json:"route,omitempty"`
	Derived string `json:"derived,omitempty"`
	// Operation, RootFields and Positions describe a GraphQL request.
	Operation  string   `json:"operation,omitempty"`
	RootFields []string `json:"root_fields,omitempty"`
	Positions  []string `json:"positions,omitempty"`
	// Reason names an unresolved request's class and subject.
	Reason string `json:"reason,omitempty"`
	// Class is one of the Class constants.
	Class      string   `json:"class"`
	Sites      []string `json:"sites,omitempty"`
	SDKMethods []string `json:"sdk_methods,omitempty"`
	// Directives are the //gitlab:request directives that qualified it, as
	// "<kind>: <reason>".
	Directives []string `json:"directives,omitempty"`
	// Declaration is the category of the declaration that supplied it.
	Declaration string `json:"declaration,omitempty"`
}

// ReadRecord loads the committed record from a repository root.
//
// A record with no action in it is an error rather than an empty record, for
// the reason the request inventory gives: every reader answers a question of
// the form "which of these does the derivation say", and an empty file answers
// all of them with "nothing", which is the loudest possible wrong answer.
func ReadRecord(root string) (Record, error) {
	target := filepath.Join(root, filepath.FromSlash(RecordPath))
	content, err := os.ReadFile(target) //#nosec G304 -- the path is derived from the repository root
	if err != nil {
		return Record{}, fmt.Errorf("read the action request record: %w", err)
	}
	var record Record
	if unmarshalErr := json.Unmarshal(content, &record); unmarshalErr != nil {
		return Record{}, fmt.Errorf("parse %s: %w", RecordPath, unmarshalErr)
	}
	if len(record.Actions) == 0 {
		return Record{}, fmt.Errorf("%s holds no action: run `make gen-action-grants`", RecordPath)
	}
	return record, nil
}

// RenderRecord marshals actions as the committed record, under its note. An
// action with no path is written with an empty list rather than none, since a
// reader indexes it, and no action at all is written as an empty list too.
//
// The marshal goes through [cmdutil.Must] because it cannot fail on a value
// built out of strings, ints and slices of them.
func RenderRecord(actions []RecordAction) []byte {
	record := Record{Note: RecordNote, Actions: make([]RecordAction, 0, len(actions))}
	for _, action := range actions {
		if action.Paths == nil {
			action.Paths = [][]int{}
		}
		record.Actions = append(record.Actions, action)
	}
	return cmdutil.Must(json.MarshalIndent(record, "", "  "))
}
