//go:build e2e && enterprise

// auditeventextras_ee_test.go covers the audit-event list actions the e2e
// gap audit reported as unexercised (audit_event.list_instance, list_group,
// list_project). TestMeta_AuditEvents in enterprise_ee_test.go drives the
// same endpoints through a shared helper that passes the action name as a
// variable, which the static gap scanner cannot attribute; this file calls
// each action with a literal name so coverage is provable, and asserts on
// events generated by its own fixture mutations.
//
// Build tag: e2e && enterprise.
package suite

import (
	"context"
	"testing"
	"time"

	"github.com/jmrplens/gitlab-mcp-server/v2/internal/tools/auditevents"
	"github.com/jmrplens/gitlab-mcp-server/v2/internal/tools/groups"
	"github.com/jmrplens/gitlab-mcp-server/v2/internal/tools/projects"
)

// aeExtrasRetryable classifies audit-event list retry states: transient API
// failures and the eventual-consistency window before events are indexed.
func aeExtrasRetryable(err error, count int) (bool, string) {
	if err != nil {
		return isRetryableError(err), "transient audit event API error"
	}
	if count == 0 {
		return true, "audit events not indexed yet"
	}
	return false, ""
}

// TestMeta_AuditEventListActions exercises list_project, list_group, and
// list_instance with literal action names via the gitlab_audit_event
// meta-tool against a live GitLab Premium/Ultimate instance.
//
// The test creates and mutates a group and a project so scoped audit events
// are guaranteed to exist, then polls each list action until events surface.
// The instance-level list requires an administrator token and is gated with
// the shared admin capability check like other admin EE tests.
//
// Build tag: e2e && enterprise. Mode: EE. Surface: meta.
func TestMeta_AuditEventListActions(t *testing.T) {
	t.Parallel()
	if !sess.enterprise {
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), 180*time.Second)
	defer cancel()

	e2e := NewE2EContext(t)
	grp := CreateGroupMeta(ctx, e2e, sess.meta, "ae-extra")
	proj := createProjectMeta(ctx, t, sess.meta)

	// Mutations below guarantee at least one audit event per scope.
	_, grpErr := callToolOn[groups.Output](ctx, sess.meta, "gitlab_group", map[string]any{
		"action": "update",
		"params": map[string]any{
			"group_id":    grp.gidStr(),
			"description": "E2E audit event list fixture",
		},
	})
	requireNoError(t, grpErr, "update group to generate an audit event")
	_, projErr := callToolOn[projects.Output](ctx, sess.meta, "gitlab_project", map[string]any{
		"action": "update",
		"params": map[string]any{
			"project_id":  proj.pidStr(),
			"description": "E2E audit event list fixture",
		},
	})
	requireNoError(t, projErr, "update project to generate an audit event")

	t.Run("Meta/AuditEvent/ListProjectLiteral", func(t *testing.T) {
		out, err := retryWithBackoff(ctx, t, "audit event list_project", 8, func(int) (auditevents.ListOutput, bool, string, error) {
			out, err := callToolOn[auditevents.ListOutput](ctx, sess.meta, "gitlab_audit_event", map[string]any{
				"action": "list_project",
				"params": map[string]any{
					"project_id": proj.pidStr(),
					"per_page":   20,
				},
			})
			retry, reason := aeExtrasRetryable(err, len(out.AuditEvents))
			if err == nil && len(out.AuditEvents) == 0 {
				err = geExtrasError("list_project returned no audit events")
			}
			return out, retry, reason, err
		})
		requirePremiumFeature(t, err, "project audit events")
		requireTruef(t, out.AuditEvents[0].ID > 0, "project audit event ID should be positive")
		t.Logf("Project audit events: %d", len(out.AuditEvents))
	})

	t.Run("Meta/AuditEvent/ListGroupLiteral", func(t *testing.T) {
		out, err := retryWithBackoff(ctx, t, "audit event list_group", 8, func(int) (auditevents.ListOutput, bool, string, error) {
			out, err := callToolOn[auditevents.ListOutput](ctx, sess.meta, "gitlab_audit_event", map[string]any{
				"action": "list_group",
				"params": map[string]any{
					"group_id": grp.gidStr(),
					"per_page": 20,
				},
			})
			retry, reason := aeExtrasRetryable(err, len(out.AuditEvents))
			if err == nil && len(out.AuditEvents) == 0 {
				err = geExtrasError("list_group returned no audit events")
			}
			return out, retry, reason, err
		})
		requirePremiumFeature(t, err, "group audit events")
		requireTruef(t, out.AuditEvents[0].ID > 0, "group audit event ID should be positive")
		t.Logf("Group audit events: %d", len(out.AuditEvents))
	})

	t.Run("Meta/AuditEvent/ListInstanceLiteral", func(t *testing.T) {
		requireAdminCapability(t) //nolint:contextcheck // The capability probe owns its own short-lived context by design.
		out, err := retryWithBackoff(ctx, t, "audit event list_instance", 8, func(int) (auditevents.ListOutput, bool, string, error) {
			out, err := callToolOn[auditevents.ListOutput](ctx, sess.meta, "gitlab_audit_event", map[string]any{
				"action": "list_instance",
				"params": map[string]any{
					"per_page": 20,
				},
			})
			retry, reason := aeExtrasRetryable(err, len(out.AuditEvents))
			if err == nil && len(out.AuditEvents) == 0 {
				err = geExtrasError("list_instance returned no audit events")
			}
			return out, retry, reason, err
		})
		requirePremiumFeature(t, err, "instance audit events")
		requireTruef(t, out.AuditEvents[0].ID > 0, "instance audit event ID should be positive")
		t.Logf("Instance audit events: %d", len(out.AuditEvents))
	})
}
