package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/jmrplens/gitlab-mcp-server/v3/cmd/internal/docgen"
)

// renderRecordPage draws the committed record as the page the repository
// publishes.
//
// It reads the record and nothing else. That is what makes the page a member
// of update-all while the record is not: refreshing the figures needs a booted
// GitLab, redrawing them from the committed figures needs a checkout, and the
// two are separate targets for the same reason bench-resources and
// bench-resources-render are.
//
// The tables go through [docgen.RenderMarkdownTable] rather than being written
// by hand, because everything under docs/ is held to cmd/format_md_tables by
// `make audit-docs`, and a generated page that arrived unpadded would fail
// that check on the first push.
func renderRecordPage(doc *coverageRecord) string {
	var b strings.Builder
	writeRecordPageHeader(&b)
	writeRecordCoverage(&b, doc)
	writeRecordProvenance(&b, doc)
	writeRecordFixtures(&b, doc)
	writeRecordStates(&b, doc)
	writeRecordPageFooter(&b)
	return b.String()
}

// recordPageOrder lists the record's keys with the two known runtimes first,
// so the page does not reorder itself when an unexpected key appears.
func recordPageOrder(doc *coverageRecord) []string {
	var order []string
	for _, key := range recordRuntimes {
		if _, present := doc.Runtimes[key]; present {
			order = append(order, key)
		}
	}
	var extra []string
	for key := range doc.Runtimes {
		if !isRecordKey(key) {
			extra = append(extra, key)
		}
	}
	sort.Strings(extra)
	return append(order, extra...)
}

// writeRecordPageHeader writes the title, the Diátaxis header the sibling
// pages carry, and what the page is.
func writeRecordPageHeader(b *strings.Builder) {
	b.WriteString(`# E2E Coverage

> **Diátaxis type**: Reference
> **Audience**: 🔧 Maintainers, contributors
> **Prerequisites**: Docker for the runs that produce these figures
>
> Generated by ` + "`" + pageRegenerate + "`" + ` from ` + "`" + recordRelPath + "`" + `. Do not edit by hand.

---

This is what the end-to-end suite asserts, measured rather than claimed. The
suite records every MCP call a test makes and every action the server's own
span says it dispatched; ` + "`cmd/audit_e2e_coverage`" + ` compares those records with
the catalog the instance served and gives every runtime x surface x mode x
action exactly one state. The figures below are the fold of that comparison
for the two Docker runtimes, committed so the question "how much of the
catalog does the suite actually cover" can be answered from a checkout.

A share here is of the **catalog the instance served**, which is not the same
as the catalog this tree builds today: the record carries the size it was
measured against, and ` + "`make check-e2e-coverage-record`" + ` says so when the two
have drifted.

- **L1** — asserted on at least one surface, in the default mode.
- **L2** — asserted on the dynamic surface, which is the one a client gets
  without configuring anything.
- **L3** — asserted on all three surfaces.

An action is *asserted* only when a passing test asked for it, expected it to
work, got that, and the server's span confirmed it dispatched exactly the
action the call named. Every weaker outcome (a sweep, an error path, a
refusal, a safe-mode preview, a cleanup) is counted apart, in the state tables
further down.

`)
}

// writeRecordCoverage writes the headline table, one row per runtime.
func writeRecordCoverage(b *strings.Builder, doc *coverageRecord) {
	rows := make([][]string, 0, len(doc.Runtimes))
	for _, key := range recordPageOrder(doc) {
		entry := doc.Runtimes[key]
		if entry == nil {
			continue
		}
		rows = append(rows, []string{
			"`" + key + "`", entry.Runtime, entry.RetrievedAt,
			strconv.Itoa(entry.Summary.CatalogActions),
			fmt.Sprintf("%d (%.1f%%)", entry.Summary.L1, percent(entry.Summary.L1, entry.Summary.CatalogActions)),
			fmt.Sprintf("%d (%.1f%%)", entry.Summary.L2, percent(entry.Summary.L2, entry.Summary.CatalogActions)),
			fmt.Sprintf("%d (%.1f%%)", entry.Summary.L3, percent(entry.Summary.L3, entry.Summary.CatalogActions)),
			strconv.Itoa(entry.Summary.TestCalls),
		})
	}
	b.WriteString("## Coverage\n\n")
	b.WriteString(docgen.RenderMarkdownTable(
		[]string{"Runtime", "Edition/tier", "Measured", "Catalog actions", "L1", "L2", "L3", "Test calls"},
		[]docgen.Alignment{
			docgen.AlignLeft, docgen.AlignLeft, docgen.AlignLeft, docgen.AlignRight,
			docgen.AlignRight, docgen.AlignRight, docgen.AlignRight, docgen.AlignRight,
		},
		rows,
	))
	b.WriteString("\nThe actions behind each level are listed by id in `" + recordRelPath +
		"`, under `levels.l1`, `levels.l2` and `levels.l3`.\n\n")
}

// writeRecordProvenance writes one row per package that ran, which is where
// the revision and the instance version live.
func writeRecordProvenance(b *strings.Builder, doc *coverageRecord) {
	var rows [][]string
	for _, key := range recordPageOrder(doc) {
		entry := doc.Runtimes[key]
		if entry == nil {
			continue
		}
		for _, run := range entry.Runs {
			rows = append(rows, []string{
				"`" + key + "`", "`" + run.Package + "`", run.Requirement, run.Status,
				run.GitLabVersion, yesNo(run.TierConfirmed), shortCommit(run.Commit),
			})
		}
	}
	b.WriteString("## Provenance\n\n")
	b.WriteString(docgen.RenderMarkdownTable(
		[]string{"Runtime", "Package", "Requires", "Status", "GitLab", "Tier confirmed", "Commit"},
		nil, rows,
	))
	b.WriteString("\nA tier that is not confirmed came from a setting rather than from the " +
		"instance license, which means the catalog the share is divided by may hold actions " +
		"that instance would refuse. An unlicensed GitLab reports no license at all, so the " +
		"`ce` half is expected to read `no` here.\n\n")
}

// writeRecordFixtures writes what each package had available, and what an
// absent fixture does to the figures above.
func writeRecordFixtures(b *strings.Builder, doc *coverageRecord) {
	var rows [][]string
	for _, key := range recordPageOrder(doc) {
		entry := doc.Runtimes[key]
		if entry == nil {
			continue
		}
		for _, run := range entry.Runs {
			rows = append(rows, []string{
				"`" + key + "`", "`" + run.Package + "`", yesNo(run.Fixtures.Runner),
				yesNo(run.Fixtures.FixtureService), yesNo(run.Fixtures.Bitbucket), yesNo(run.Fixtures.GHToken),
			})
		}
	}
	b.WriteString("## Fixture profile\n\n")
	b.WriteString(docgen.RenderMarkdownTable(
		[]string{"Runtime", "Package", "CI runner", "Fixture service", "Bitbucket", "GitHub token"},
		nil, rows,
	))
	b.WriteString("\nThe profile is recorded per package and the two halves need not agree. " +
		"A scenario whose precondition the runtime cannot provide is **absent** rather than " +
		"failing, so a fixture one half had and the other did not moves every action that " +
		"needs it out of the other half's asserted count without leaving a failure behind. " +
		"Compare the rows before comparing the two halves' shares: a lower figure may be a " +
		"fixture that was down rather than a scenario that is missing.\n\n")
}

// writeRecordStates writes the state histograms, one section per runtime.
func writeRecordStates(b *strings.Builder, doc *coverageRecord) {
	b.WriteString("## States\n\n")
	b.WriteString("Every cell of the default mode, counted per surface: the credit a passing " +
		"assertion earned, then the shallower credits, then the reasons there is none. " +
		"`unservable` is a cell the surface cannot reach at all (no individual tool, a " +
		"shadowed tool name, a scope that withheld the group), and `absent` is a servable " +
		"cell nothing called.\n\n")
	writeCapabilityGrains(b)
	for _, key := range recordPageOrder(doc) {
		entry := doc.Runtimes[key]
		if entry == nil {
			continue
		}
		b.WriteString("### " + key + "\n\n")
		b.WriteString(renderStateTable("Surface", entry.Summary.States))
		b.WriteString("\n")
		writeRecordCapabilities(b, key, entry)
	}
}

// writeCapabilityGrains states the grain each capability kind is counted at,
// drawn from [capabilityGrains] itself so the page cannot describe a grain the
// fold does not use.
func writeCapabilityGrains(b *strings.Builder) {
	rows := make([][]string, 0, len(capabilityGrains))
	for _, kind := range sortedKeys(capabilityGrains) {
		rows = append(rows, []string{"`" + kind + "`", capabilityGrains[kind].String()})
	}
	b.WriteString("The capabilities beside the tools are classified on the same states, each " +
		"counted at the grain its content varies along:\n\n")
	b.WriteString(docgen.RenderMarkdownTable([]string{"Capability", "One cell per item per"}, nil, rows))
	b.WriteString("\nThe server registers its resources, prompts, completions and subscribable kinds " +
		"from the capability surface alone, so neither the tool surface nor the protective mode " +
		"changes what a session is served, and a cell per shape would be one nothing could fill " +
		"differently from its twin. Subscriptions exist on the full capability surface only. " +
		"`gitlab://tools` and `gitlab://tools/{id}` are the exception, counted as `tool_manifest`: " +
		"they list what the session's tool surface registered after the read-only and safe passes, " +
		"so they change along all three. The elicitation flows and the protective modes are reached " +
		"through the actions a surface serves in a mode, and are counted where those are.\n\n")
}

// writeRecordCapabilities writes one runtime's capability histogram, beside
// what it is counted against: the capability surfaces the entry recorded, or,
// for an entry recorded before them, the grain its figures were counted at.
//
// A runtime measured before the capability cells existed carries no histogram,
// and gets nothing here: a sentence introducing an empty table would read as a
// run that watched nothing rather than as a record that says nothing.
func writeRecordCapabilities(b *strings.Builder, key string, entry *recordEntry) {
	if len(entry.Summary.Capabilities) == 0 {
		return
	}
	if len(entry.CapabilitySurfaces) == 0 {
		b.WriteString("This entry was recorded before the grain above: each of its capability rows counts " +
			"every item once per surface x mode, whatever the kind, so an item every shape served is as " +
			"many cells as there are shapes. `" + recordRegenerate + "-" + key + "` re-records it at " +
			"the grain above.\n\n")
	} else {
		b.WriteString("What each capability surface served, which is what the capability rows are counted against:\n\n")
		b.WriteString(renderCapabilitySurfaceTable(entry.CapabilitySurfaces))
		b.WriteString("\n")
	}
	b.WriteString(renderStateTable("Capability", entry.Summary.Capabilities))
	b.WriteString("\n")
}

// renderCapabilitySurfaceTable draws the capability surface rows in the order
// the record holds them.
func renderCapabilitySurfaceTable(surfaces []capabilitySurfaceRow) string {
	rows := make([][]string, 0, len(surfaces))
	for _, surface := range surfaces {
		rows = append(rows, []string{
			"`" + surface.Capabilities + "`", strconv.Itoa(surface.Sessions), strconv.Itoa(surface.Shapes),
			strconv.Itoa(surface.Resources), strconv.Itoa(surface.Prompts), strconv.Itoa(surface.Completions),
			strconv.Itoa(surface.SubscribableKinds),
		})
	}
	return docgen.RenderMarkdownTable(
		[]string{"Capability surface", "Sessions", "Shapes", "Resources", "Prompts", "Completions", "Subscribable kinds"},
		[]docgen.Alignment{
			docgen.AlignLeft, docgen.AlignRight, docgen.AlignRight, docgen.AlignRight,
			docgen.AlignRight, docgen.AlignRight, docgen.AlignRight,
		},
		rows,
	)
}

// renderStateTable draws one histogram with a column per state, and is the one
// implementation of that table: [writeStateTable], which is what a run's
// Markdown summary puts in GITHUB_STEP_SUMMARY, prints what this returns.
//
// The columns are every state, in the order [markdownStates] fixes, even the
// ones no runtime reached: a column that came and went with the data would
// make every refresh a diff of the header as well as of the figures.
//
// The rows are ordered by [surfaceOrder] and then by name, which is right for
// both callers rather than a surface-table rule imposed on the capability
// table: surfaceOrder ranks everything that is not one of the three surfaces
// the same, so the capability keys fall through to alphabetical on their own.
// It used to take an order function for that, and the only two arguments ever
// passed produced identical output.
func renderStateTable(first string, histogram map[string]map[state]int) string {
	headers := make([]string, 0, len(markdownStates)+1)
	headers = append(headers, first)
	alignments := make([]docgen.Alignment, 0, len(markdownStates)+1)
	alignments = append(alignments, docgen.AlignLeft)
	for _, s := range markdownStates {
		headers = append(headers, string(s))
		alignments = append(alignments, docgen.AlignRight)
	}
	keys := make([]string, 0, len(histogram))
	for key := range histogram {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if surfaceOrder(keys[i]) != surfaceOrder(keys[j]) {
			return surfaceOrder(keys[i]) < surfaceOrder(keys[j])
		}
		return keys[i] < keys[j]
	})
	rows := make([][]string, 0, len(keys))
	for _, key := range keys {
		row := make([]string, 0, len(markdownStates)+1)
		row = append(row, "`"+key+"`")
		for _, s := range markdownStates {
			row = append(row, strconv.Itoa(histogram[key][s]))
		}
		rows = append(rows, row)
	}
	return docgen.RenderMarkdownTable(headers, alignments, rows)
}

// writeRecordPageFooter writes how the figures are refreshed.
func writeRecordPageFooter(b *strings.Builder) {
	b.WriteString(`## Refreshing this page

The figures come from a Docker run of both halves and cannot be regenerated
without one:

` + "```bash" + `
make test-e2e-ce            # boots an unlicensed GitLab and runs common + ce
make test-e2e-ee            # boots a licensed GitLab and runs common + ee
make e2e-coverage-record    # folds both runs into ` + recordRelPath + `
` + "```" + `

Each half can be refreshed alone (` + "`make e2e-coverage-record-ce`" + `,
` + "`make e2e-coverage-record-ee`" + `): the write folds into the committed document and
leaves the other half exactly as it was.

This page is a rendering, so it needs no GitLab:

` + "```bash" + `
` + pageRegenerate + `  # redraw from the committed record
make check-e2e-coverage-page     # is this page what the record renders to
make check-e2e-coverage-record   # are the recorded figures themselves sound
` + "```" + `

CI runs both, and on different terms. The record is judged on every push,
because nothing in this repository can regenerate those figures and a stale one
is the only thing left to catch. The page is judged only where the freshness
gates apply, because the renderer that draws it is code here: a change to it
makes this file stale on purpose, and the layer that refreshes it is the one
that should be asked.
`)
}

// yesNo spells a recorded flag.
func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

// shortCommit renders a recorded revision, abbreviated the way git logs it
// and left empty for a run of a tree git could not see.
func shortCommit(commit string) string {
	if commit == "" {
		return "—"
	}
	if len(commit) > 12 {
		return "`" + commit[:12] + "`"
	}
	return "`" + commit + "`"
}
